# Amsterda urban studies

In [2]:
import pandas as pd
import requests

## APIs

### Energy label

#### Endpoint

https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel

#### Response

In [1]:
dict = {
    "_embedded": {
        "energielabel": [
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1011PG~171~~~~0363010001011891~",
                        "title": "20160601~1011PG~171~~~~0363010001011891~",
                        "id": "20160601~1011PG~171~~~~0363010001011891~"
                    }
                },
                "id": "20160601~1011PG~171~~~~0363010001011891~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "1Rgielabel.nl",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Maisonnette",
                "gebouwsubtype": "Tussenmidden",
                "sbicode": "",
                "postcode": "1011PG",
                "huisnummer": 171,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010001011891",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 2002,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "B",
                "energieindex": "1,21",
                "energieindexMetEmgForfaitair": "1,21",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "2796,08",
                "berekendeEnergieverbruik": "52754,00"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1015JJ~7~2~~~0363010000647799~",
                        "title": "20160601~1015JJ~7~2~~~0363010000647799~",
                        "id": "20160601~1015JJ~7~2~~~0363010000647799~"
                    }
                },
                "id": "20160601~1015JJ~7~2~~~0363010000647799~",
                "registratiedatum": "2016-06-02",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Innax Bouwkundig adviseurs BV",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Tussenmidden",
                "sbicode": "",
                "postcode": "1015JJ",
                "huisnummer": 7,
                "huisletter": "",
                "huisnummertoevoeging": "2",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000647799",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1905,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "B",
                "energieindex": "1,39",
                "energieindexMetEmgForfaitair": "1,39",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "1883,73",
                "berekendeEnergieverbruik": "36381,54"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1015NG~177~1~~~0363010000954233~",
                        "title": "20160601~1015NG~177~1~~~0363010000954233~",
                        "id": "20160601~1015NG~177~1~~~0363010000954233~"
                    }
                },
                "id": "20160601~1015NG~177~1~~~0363010000954233~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Eneco installatiebedrijven",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Rekenmethodiek Definitief Energielabel, versie 1.2, 16 september 2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Maisonnette",
                "gebouwsubtype": "Tussendak",
                "sbicode": "",
                "postcode": "1015NG",
                "huisnummer": 177,
                "huisletter": "",
                "huisnummertoevoeging": "1",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000954233",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1930,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "F",
                "energieindex": "",
                "energieindexMetEmgForfaitair": "",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "0,00",
                "berekendeEnergieverbruik": "116814,21"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1015XT~48~H~~~0363010000736175~",
                        "title": "20160601~1015XT~48~H~~~0363010000736175~",
                        "id": "20160601~1015XT~48~H~~~0363010000736175~"
                    }
                },
                "id": "20160601~1015XT~48~H~~~0363010000736175~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Mijnbouwhulp.nl",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Rekenmethodiek Definitief Energielabel, versie 1.2, 16 september 2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Tussenvloer",
                "sbicode": "",
                "postcode": "1015XT",
                "huisnummer": 48,
                "huisletter": "",
                "huisnummertoevoeging": "H",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000736175",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1930,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "D",
                "energieindex": "",
                "energieindexMetEmgForfaitair": "",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "0,00",
                "berekendeEnergieverbruik": "67499,07"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1018NM~144~~A~~0363010012094717~",
                        "title": "20160601~1018NM~144~~A~~0363010012094717~",
                        "id": "20160601~1018NM~144~~A~~0363010012094717~"
                    }
                },
                "id": "20160601~1018NM~144~~A~~0363010012094717~",
                "registratiedatum": "2016-06-14",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woningstichting Eigen Haard",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Maisonnette",
                "gebouwsubtype": "Tussenvloer",
                "sbicode": "",
                "postcode": "1018NM",
                "huisnummer": 144,
                "huisletter": "A",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010012094717",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1880,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "1,13",
                "energieindexMetEmgForfaitair": "1,13",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "1801,83",
                "berekendeEnergieverbruik": "33671,96"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1018NM~144~~C~~0363010012094719~",
                        "title": "20160601~1018NM~144~~C~~0363010012094719~",
                        "id": "20160601~1018NM~144~~C~~0363010012094719~"
                    }
                },
                "id": "20160601~1018NM~144~~C~~0363010012094719~",
                "registratiedatum": "2016-06-14",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woningstichting Eigen Haard",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Tussenmidden",
                "sbicode": "",
                "postcode": "1018NM",
                "huisnummer": 144,
                "huisletter": "C",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010012094719",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1880,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "1,13",
                "energieindexMetEmgForfaitair": "1,13",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "1289,54",
                "berekendeEnergieverbruik": "23723,78"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1018NM~144~~D~~0363010012094720~",
                        "title": "20160601~1018NM~144~~D~~0363010012094720~",
                        "id": "20160601~1018NM~144~~D~~0363010012094720~"
                    }
                },
                "id": "20160601~1018NM~144~~D~~0363010012094720~",
                "registratiedatum": "2016-06-14",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woningstichting Eigen Haard",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Maisonnette",
                "gebouwsubtype": "Tussendak",
                "sbicode": "",
                "postcode": "1018NM",
                "huisnummer": 144,
                "huisletter": "D",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010012094720",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1880,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "1,01",
                "energieindexMetEmgForfaitair": "1,01",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "1725,53",
                "berekendeEnergieverbruik": "32151,12"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1018NN~148~~B~~0363010012094723~",
                        "title": "20160601~1018NN~148~~B~~0363010012094723~",
                        "id": "20160601~1018NN~148~~B~~0363010012094723~"
                    }
                },
                "id": "20160601~1018NN~148~~B~~0363010012094723~",
                "registratiedatum": "2016-06-14",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woningstichting Eigen Haard",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Tussenmidden",
                "sbicode": "",
                "postcode": "1018NN",
                "huisnummer": 148,
                "huisletter": "B",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010012094723",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1880,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "1,10",
                "energieindexMetEmgForfaitair": "1,10",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "1801,46",
                "berekendeEnergieverbruik": "33477,03"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1018NN~148~~D~~0363010012094725~",
                        "title": "20160601~1018NN~148~~D~~0363010012094725~",
                        "id": "20160601~1018NN~148~~D~~0363010012094725~"
                    }
                },
                "id": "20160601~1018NN~148~~D~~0363010012094725~",
                "registratiedatum": "2016-06-14",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woningstichting Eigen Haard",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Maisonnette",
                "gebouwsubtype": "Tussendak",
                "sbicode": "",
                "postcode": "1018NN",
                "huisnummer": 148,
                "huisletter": "D",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010012094725",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1880,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "1,07",
                "energieindexMetEmgForfaitair": "1,07",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "2942,61",
                "berekendeEnergieverbruik": "55266,27"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1018TZ~44~~~~0363010000673388~",
                        "title": "20160601~1018TZ~44~~~~0363010000673388~",
                        "id": "20160601~1018TZ~44~~~~0363010000673388~"
                    }
                },
                "id": "20160601~1018TZ~44~~~~0363010000673388~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Energielabel Hofstad",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Rekenmethodiek Definitief Energielabel, versie 1.2, 16 september 2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Hoekdak",
                "sbicode": "",
                "postcode": "1018TZ",
                "huisnummer": 44,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000673388",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1985,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "C",
                "energieindex": "",
                "energieindexMetEmgForfaitair": "",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "0,00",
                "berekendeEnergieverbruik": "74612,91"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1019GW~41~~~~0363010001162986~",
                        "title": "20160601~1019GW~41~~~~0363010001162986~",
                        "id": "20160601~1019GW~41~~~~0363010001162986~"
                    }
                },
                "id": "20160601~1019GW~41~~~~0363010001162986~",
                "registratiedatum": "2016-06-03",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Innax Bouwkundig adviseurs BV",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Maisonnette",
                "gebouwsubtype": "Tussendak",
                "sbicode": "",
                "postcode": "1019GW",
                "huisnummer": 41,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010001162986",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 2004,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "0,93",
                "energieindexMetEmgForfaitair": "0,93",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "3522,95",
                "berekendeEnergieverbruik": "57470,56"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1019HD~105~~~~0363010001038167~",
                        "title": "20160601~1019HD~105~~~~0363010001038167~",
                        "id": "20160601~1019HD~105~~~~0363010001038167~"
                    }
                },
                "id": "20160601~1019HD~105~~~~0363010001038167~",
                "registratiedatum": "2016-06-09",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Duresta Real Estate Solutions BV",
                "opnametype": "",
                "status": "",
                "berekeningstype": "ISSO75.3, versie 3.0, oktober 2011",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "U",
                "gebouwtype": "",
                "gebouwsubtype": "",
                "sbicode": "81",
                "postcode": "1019HD",
                "huisnummer": 105,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010001038167",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 2006,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "0,92",
                "energieindexMetEmgForfaitair": "0,92",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "45,85",
                "berekendeEnergieverbruik": "610,20"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1019LG~465~~~~0363010000953261~",
                        "title": "20160601~1019LG~465~~~~0363010000953261~",
                        "id": "20160601~1019LG~465~~~~0363010000953261~"
                    }
                },
                "id": "20160601~1019LG~465~~~~0363010000953261~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Energetisch- en Bouwkundig Adviesbureau Peters",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Rekenmethodiek Definitief Energielabel, versie 1.2, 16 september 2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Hoekmidden",
                "sbicode": "",
                "postcode": "1019LG",
                "huisnummer": 465,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000953261",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1995,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "B",
                "energieindex": "",
                "energieindexMetEmgForfaitair": "",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "0,00",
                "berekendeEnergieverbruik": "52349,89"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1025HT~531~~~~0363010000666241~",
                        "title": "20160601~1025HT~531~~~~0363010000666241~",
                        "id": "20160601~1025HT~531~~~~0363010000666241~"
                    }
                },
                "id": "20160601~1025HT~531~~~~0363010000666241~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "De Label Expert",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Rekenmethodiek Definitief Energielabel, versie 1.2, 16 september 2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Hoekmidden",
                "sbicode": "",
                "postcode": "1025HT",
                "huisnummer": 531,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000666241",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1970,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "F",
                "energieindex": "",
                "energieindexMetEmgForfaitair": "",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "0,00",
                "berekendeEnergieverbruik": "94056,68"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1025MS~54~~~~0363010000981826~",
                        "title": "20160601~1025MS~54~~~~0363010000981826~",
                        "id": "20160601~1025MS~54~~~~0363010000981826~"
                    }
                },
                "id": "20160601~1025MS~54~~~~0363010000981826~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Labelnu",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Rekenmethodiek Definitief Energielabel, versie 1.2, 16 september 2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Rijwoning tussen",
                "gebouwsubtype": "",
                "sbicode": "",
                "postcode": "1025MS",
                "huisnummer": 54,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000981826",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1995,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "B",
                "energieindex": "",
                "energieindexMetEmgForfaitair": "",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "0,00",
                "berekendeEnergieverbruik": "73880,56"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1033EK~10~~~~0363010000880303~",
                        "title": "20160601~1033EK~10~~~~0363010000880303~",
                        "id": "20160601~1033EK~10~~~~0363010000880303~"
                    }
                },
                "id": "20160601~1033EK~10~~~~0363010000880303~",
                "registratiedatum": "2016-06-06",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woning Advies Nederland B.V.",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Maisonnette",
                "gebouwsubtype": "Tussenmidden",
                "sbicode": "",
                "postcode": "1033EK",
                "huisnummer": 10,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000880303",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1922,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "D",
                "energieindex": "1,87",
                "energieindexMetEmgForfaitair": "1,87",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "4181,87",
                "berekendeEnergieverbruik": "80916,65"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1034NM~42~~~~0363010000893669~",
                        "title": "20160601~1034NM~42~~~~0363010000893669~",
                        "id": "20160601~1034NM~42~~~~0363010000893669~"
                    }
                },
                "id": "20160601~1034NM~42~~~~0363010000893669~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woningstichting Rochdale",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Hoekvloer",
                "sbicode": "",
                "postcode": "1034NM",
                "huisnummer": 42,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000893669",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1977,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "C",
                "energieindex": "1,50",
                "energieindexMetEmgForfaitair": "1,50",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "2673,24",
                "berekendeEnergieverbruik": "50582,99"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1036KL~26~~~~0363010011211107~",
                        "title": "20160601~1036KL~26~~~~0363010011211107~",
                        "id": "20160601~1036KL~26~~~~0363010011211107~"
                    }
                },
                "id": "20160601~1036KL~26~~~~0363010011211107~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Het Labelhuis",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Rekenmethodiek Definitief Energielabel, versie 1.2, 16 september 2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Rijwoning tussen",
                "gebouwsubtype": "",
                "sbicode": "",
                "postcode": "1036KL",
                "huisnummer": 26,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010011211107",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 2010,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "",
                "energieindexMetEmgForfaitair": "",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "0,00",
                "berekendeEnergieverbruik": "61687,38"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1051HZ~10~1~~~0363010000845715~",
                        "title": "20160601~1051HZ~10~1~~~0363010000845715~",
                        "id": "20160601~1051HZ~10~1~~~0363010000845715~"
                    }
                },
                "id": "20160601~1051HZ~10~1~~~0363010000845715~",
                "registratiedatum": "2016-09-16",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woning Advies Nederland B.V.",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Tussenmidden",
                "sbicode": "",
                "postcode": "1051HZ",
                "huisnummer": 10,
                "huisletter": "",
                "huisnummertoevoeging": "1",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000845715",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1920,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "C",
                "energieindex": "1,52",
                "energieindexMetEmgForfaitair": "1,52",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "2312,57",
                "berekendeEnergieverbruik": "44367,32"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1051HZ~10~3~~~0363010000845717~",
                        "title": "20160601~1051HZ~10~3~~~0363010000845717~",
                        "id": "20160601~1051HZ~10~3~~~0363010000845717~"
                    }
                },
                "id": "20160601~1051HZ~10~3~~~0363010000845717~",
                "registratiedatum": "2016-09-16",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woning Advies Nederland B.V.",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Tussendak",
                "sbicode": "",
                "postcode": "1051HZ",
                "huisnummer": 10,
                "huisletter": "",
                "huisnummertoevoeging": "3",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000845717",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1920,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "C",
                "energieindex": "1,73",
                "energieindexMetEmgForfaitair": "1,73",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "3117,34",
                "berekendeEnergieverbruik": "60233,39"
            }
        ]
    },
    "_links": {
        "self": {
            "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel"
        },
        "next": {
            "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel?page=2"
        }
    },
    "page": {
        "number": 1,
        "size": 20
    }
}

In [2]:
dict.keys()

dict_keys(['_embedded', '_links', 'page'])

In [6]:
dict['_embedded'].keys()

dict_keys(['energielabel'])

In [10]:
dict['_embedded']['energielabel'][0].keys()

dict_keys(['_links', 'id', 'registratiedatum', 'opnamedatum', 'metingGeldigTot', 'certificaathouder', 'opnametype', 'status', 'berekeningstype', 'isOpBasisVanReferentieGebouw', 'gebouwklasse', 'gebouwtype', 'gebouwsubtype', 'sbicode', 'postcode', 'huisnummer', 'huisletter', 'huisnummertoevoeging', 'detailaanduiding', 'bagVerblijfsobjectId', 'bagLigplaatsId', 'bagStandplaatsId', 'bagPandIds', 'projectnaam', 'projectobject', 'bouwjaar', 'gebruiksoppervlakteThermischeZone', 'compactheid', 'energieklasse', 'energieindex', 'energieindexMetEmgForfaitair', 'eisEnergiebehoefte', 'primaireFossieleEnergie', 'primaireFossieleEnergieEmgForfaitair', 'aandeelHernieuwbareEnergie', 'aandeelHernieuwbareEnergieEmgForfaitair', 'temperatuuroverschrijding', 'warmtebehoefte', 'energiebehoefte', 'eisPrimaireFossieleEnergie', 'eisAandeelHernieuwbareEnergie', 'eisTemperatuuroverschrijding', 'berekendeCo2Emissie', 'berekendeEnergieverbruik'])

#### Potential hypothesis

postcode:
average house cost - average income
energy class- energy index

In [11]:
dict['_links'].keys()

dict_keys(['self', 'next'])

In [12]:
dict['_links']['self']

{'href': 'https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel'}

In [13]:
dict['_links']['next']

{'href': 'https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel?page=2'}

### Municipal real estate - Gemeentelijk vastgoed

#### Endpoint

https://data.amsterdam.nl/catalogus/65

In [45]:
url="https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten"
response_municipal = requests.get(url)
print(response_municipal.status_code)

200

#### Response

In [46]:
response_municipal.content

b'{\n  "_embedded":{\n  "gebouwobjecten":[\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/339","title":"339","objectId":339}},"objectId":339,"straatnaam":"Aldebaranplein","huisnummer":null,"huisletter":null,"huisnummertoevoeging":"2-4","huisnummeraanduiding":null,"eigendom":"Volle eigendom","bagPandIds":["0363100012062051"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[121372.063,491634.878],[121376.943,491631.063],[121391.455,491649.607],[121387.537,491652.685],[121388.672,491654.135],[121384.725,491657.232],[121384.585,491657.342],[121372.794,491642.255],[121370.318,491644.189],[121369.794,491643.519],[121367.381,491645.403],[121367.311,491645.314],[121356.804,491631.911],[121354.963,491633.353],[121353.057,491630.911],[121345.047,491637.161],[121344.739,491636.744],[121344.487,491636.933],[121344.22,491637.099],[121343.94,491637.241],[121343.647,491637.359],[121343.346,491637.45],[121343.038,491637.514],[121342.726,491637.552],[121342.411,491637.561],[121342.097,491637.544],[121341.786,491637.499],[121341.479,491637.427],[121341.181,491637.328],[121340.892,491637.204],[121340.614,491637.055],[121340.352,491636.882],[121340.105,491636.687],[121339.876,491636.471],[121339.667,491636.235],[121339.479,491635.983],[121339.314,491635.715],[121339.177,491635.442],[121339.063,491635.157],[121338.974,491634.865],[121338.91,491634.565],[121338.872,491634.262],[121338.86,491633.956],[121338.874,491633.65],[121338.914,491633.347],[121338.979,491633.048],[121339.07,491632.756],[121339.185,491632.472],[121339.323,491632.2],[121339.485,491631.94],[121339.668,491631.695],[121339.871,491631.466],[121340.093,491631.255],[121340.332,491631.064],[121339.992,491630.698],[121342.306,491628.89],[121347.98,491624.439],[121346.066,491621.962],[121347.903,491620.525],[121337.409,491607.093],[121337.345,491607.011],[121339.732,491605.125],[121339.22,491604.471],[121341.687,491602.541],[121329.884,491587.454],[121329.964,491587.405],[121333.962,491584.252],[121335.121,491585.719],[121339.042,491582.627],[121353.539,491601.144],[121348.668,491604.965],[121359.789,491619.185],[121360.875,491620.573],[121372.063,491634.878]]]]}},\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/340","title":"340","objectId":340}},"objectId":340,"straatnaam":"Alkmaarstraat","huisnummer":10,"huisletter":null,"huisnummertoevoeging":null,"huisnummeraanduiding":null,"eigendom":"Volle eigendom","bagPandIds":["0363100012097095"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[125358.8,489748.605],[125358.96,489748.99],[125348.446,489754.175],[125345.13,489755.81],[125344.271,489754.052],[125343.876,489754.343],[125339.47,489757.59],[125339.943,489758.582],[125340.33,489758.46],[125340.45,489758.84],[125333.55,489760.85],[125334.23,489762.28],[125334.34,489762.21],[125334.59,489762.53],[125327.53,489767.72],[125327.454,489767.742],[125323.269,489768.929],[125321.72,489763.87],[125320.38,489764.28],[125318.76,489759.39],[125318.08,489759.62],[125316.6,489755.16],[125319.023,489754.365],[125316.579,489749.53],[125315.0,489750.32],[125310.809,489744.89],[125315.526,489741.236],[125315.65,489741.14],[125316.31,489741.94],[125320.36,489738.829],[125320.98,489739.63],[125325.05,489736.52],[125325.69,489737.27],[125327.04,489736.11],[125326.84,489735.87],[125331.19,489732.07],[125331.92,489732.16],[125333.13,489733.55],[125335.809,489731.17],[125336.5,489731.96],[125339.42,489729.38],[125340.11,489730.16],[125346.85,489725.729],[125350.23,489730.86],[125351.244,489730.358],[125353.55,489734.3],[125352.95,489734.66],[125355.4,489738.04],[125354.84,489738.46],[125357.96,489743.79],[125357.03,489744.34],[125357.268,489744.917],[125357.282,489744.951],[125357.966,489746.608],[125358.8,489748.605]]]]}},\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/341","title":"341","objectId":341}},"objectId":341,"straatnaam":"Amstelkade","huisnummer":13,"huisletter":null,"huisnummertoevoeging":null,"huisnummeraanduiding":null,"eigendom":"Volle eigendom","bagPandIds":["0363100012103599"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[122322.447,484699.324],[122322.371,484699.666],[122321.728,484702.544],[122321.652,484702.886],[122321.499,484703.569],[122314.449,484702.029],[122315.009,484699.439],[122309.539,484698.229],[122312.999,484682.539],[122314.87,484682.92],[122314.729,484683.469],[122321.551,484684.991],[122321.799,484683.92],[122326.219,484684.88],[122326.11,484685.42],[122325.58,484685.299],[122322.447,484699.324]]]]}},\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/343","title":"343","objectId":343}},"objectId":343,"straatnaam":"Berberisstraat","huisnummer":16,"huisletter":null,"huisnummertoevoeging":null,"huisnummeraanduiding":null,"eigendom":"Volle eigendom","bagPandIds":["0363100012163016"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[122923.382,489563.258],[122898.935,489562.172],[122898.794,489565.34],[122894.908,489565.167],[122895.049,489562.0],[122885.768,489561.588],[122886.381,489547.791],[122887.659,489547.848],[122899.302,489548.365],[122899.649,489548.38],[122899.615,489549.139],[122923.959,489550.219],[122923.951,489550.441],[122923.78,489554.296],[122923.382,489563.258]]]]}},\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/344","title":"344","objectId":344}},"objectId":344,"straatnaam":"Bezaanjachtplein","huisnummer":null,"huisletter":null,"huisnummertoevoeging":"243 t/m 251","huisnummeraanduiding":null,"eigendom":"Appartementsrecht","bagPandIds":["0363100012239467"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[123011.8,491225.599],[122993.876,491201.646],[123005.372,491193.062],[123023.301,491216.992],[123011.8,491225.599]]]]}},\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/347","title":"347","objectId":347}},"objectId":347,"straatnaam":"Brigantijnkade","huisnummer":53,"huisletter":null,"huisnummertoevoeging":null,"huisnummeraanduiding":null,"eigendom":"Appartementsrecht","bagPandIds":["0363100012207608"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[127771.587,486210.758],[127756.742,486223.783],[127746.272,486211.847],[127746.218,486211.786],[127776.941,486165.789],[127782.357,486157.679],[127782.368,486157.663],[127782.522,486157.433],[127782.612,486157.497],[127782.593,486157.529],[127799.745,486177.085],[127799.525,486177.278],[127799.54,486177.295],[127790.575,486185.194],[127794.989,486190.224],[127771.587,486210.758]]]]}},\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/349","title":"349","objectId":349}},"objectId":349,"straatnaam":"Buiksloterweg","huisnummer":5,"huisletter":null,"huisnummertoevoeging":null,"huisnummeraanduiding":null,"eigendom":"Volle eigendom","bagPandIds":["0363100012164355"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[122048.585,488407.027],[122050.127,488404.884],[122046.637,488402.372],[122050.557,488396.926],[122051.003,488397.247],[122052.16,488395.64],[122055.932,488398.355],[122054.759,488399.951],[122068.799,488410.058],[122069.955,488408.451],[122073.704,488411.15],[122072.549,488412.759],[122072.979,488413.079],[122069.07,488418.519],[122065.583,488416.013],[122064.042,488418.157],[122048.585,488407.027]]]]}},\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/350","title":"350","objectId":350}},"objectId":350,"straatnaam":"Buiksloterweg","huisnummer":7,"huisletter":null,"huisnummertoevoeging":null,"huisnummeraanduiding":null,"eigendom":"Volle eigendom","bagPandIds":["0363100012066897"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[122158.631,488485.707],[122161.47,488487.756],[122157.198,488493.676],[122151.491,488489.555],[122150.466,488490.974],[122150.643,488491.113],[122150.811,488491.265],[122150.968,488491.427],[122151.113,488491.6],[122151.247,488491.781],[122151.368,488491.972],[122151.475,488492.17],[122151.57,488492.376],[122151.65,488492.587],[122151.715,488492.803],[122151.766,488493.022],[122151.802,488493.245],[122151.822,488493.47],[122151.828,488493.696],[122151.818,488493.921],[122151.793,488494.146],[122151.753,488494.368],[122151.698,488494.587],[122151.628,488494.801],[122151.544,488495.011],[122151.445,488495.214],[122151.334,488495.41],[122151.209,488495.598],[122151.072,488495.778],[122150.923,488495.947],[122150.763,488496.106],[122150.593,488496.254],[122150.412,488496.39],[122150.224,488496.514],[122150.027,488496.624],[122149.823,488496.721],[122149.613,488496.804],[122149.398,488496.873],[122149.179,488496.927],[122147.919,488498.696],[122147.352,488498.558],[122146.788,488498.406],[122146.229,488498.24],[122145.674,488498.06],[122145.123,488497.865],[122144.578,488497.657],[122144.038,488497.435],[122143.504,488497.2],[122142.976,488496.951],[122142.455,488496.689],[122141.94,488496.414],[122141.823,488496.326],[122141.716,488496.226],[122141.619,488496.116],[122141.534,488495.997],[122141.461,488495.87],[122141.401,488495.737],[122141.354,488495.598],[122141.322,488495.455],[122141.305,488495.31],[122141.302,488495.163],[122141.313,488495.017],[122141.339,488494.873],[122141.38,488494.733],[122141.434,488494.597],[122141.502,488494.467],[122141.583,488494.345],[122141.675,488494.231],[122139.006,488492.305],[122138.927,488492.43],[122138.836,488492.547],[122138.735,488492.655],[122138.623,488492.751],[122138.502,488492.836],[122138.373,488492.909],[122138.237,488492.969],[122138.097,488493.015],[122137.952,488493.046],[122137.805,488493.064],[122137.657,488493.066],[122137.509,488493.054],[122137.364,488493.028],[122137.222,488492.987],[122137.084,488492.932],[122136.953,488492.864],[122136.829,488492.783],[122136.406,488492.377],[122135.993,488491.962],[122135.59,488491.536],[122135.198,488491.1],[122134.817,488490.655],[122134.447,488490.201],[122134.088,488489.738],[122133.74,488489.266],[122133.404,488488.786],[122133.08,488488.298],[122132.768,488487.802],[122132.873,488487.655],[122134.021,488486.053],[122133.999,488485.829],[122133.993,488485.604],[122134.001,488485.379],[122134.026,488485.155],[122134.065,488484.933],[122134.119,488484.714],[122134.189,488484.5],[122134.272,488484.291],[122134.37,488484.088],[122134.481,488483.892],[122134.605,488483.704],[122134.742,488483.525],[122134.89,488483.356],[122135.05,488483.197],[122135.221,488483.05],[122135.4,488482.914],[122135.589,488482.791],[122135.786,488482.681],[122135.989,488482.585],[122136.199,488482.503],[122136.414,488482.435],[122136.633,488482.383],[122136.855,488482.345],[122137.079,488482.322],[122137.304,488482.315],[122137.529,488482.323],[122137.753,488482.346],[122137.975,488482.385],[122138.194,488482.438],[122138.408,488482.506],[122138.618,488482.589],[122138.821,488482.686],[122139.018,488482.796],[122139.206,488482.92],[122140.217,488481.516],[122140.153,488481.469],[122144.46,488475.566],[122146.96,488477.356],[122149.104,488474.489],[122147.948,488473.63],[122147.733,488473.687],[122147.516,488473.73],[122147.295,488473.758],[122147.074,488473.771],[122146.852,488473.77],[122146.631,488473.754],[122146.411,488473.724],[122146.194,488473.679],[122145.98,488473.619],[122145.77,488473.546],[122145.566,488473.459],[122145.368,488473.358],[122145.178,488473.245],[122144.995,488473.119],[122144.851,488473.006],[122144.679,488472.854],[122144.519,488472.69],[122144.369,488472.515],[122144.233,488472.331],[122144.109,488472.138],[122143.998,488471.937],[122143.902,488471.729],[122143.822,488471.423],[122143.756,488471.114],[122143.706,488470.802],[122143.671,488470.488],[122143.651,488470.173],[122143.646,488469.857],[122143.656,488469.541],[122143.682,488469.226],[122143.723,488468.913],[122143.78,488468.602],[122143.851,488468.294],[122143.937,488467.99],[122144.037,488467.69],[122144.152,488467.396],[122144.281,488467.107],[122144.424,488466.826],[122144.581,488466.551],[122144.75,488466.284],[122144.932,488466.026],[122145.127,488465.777],[122145.333,488465.538],[122145.551,488465.309],[122145.779,488465.09],[122146.018,488464.883],[122146.267,488464.688],[122146.524,488464.505],[122146.79,488464.335],[122147.065,488464.178],[122147.346,488464.034],[122147.634,488463.904],[122147.928,488463.788],[122148.227,488463.687],[122148.531,488463.6],[122148.839,488463.528],[122149.062,488463.494],[122149.287,488463.476],[122149.513,488463.472],[122149.738,488463.484],[122149.962,488463.511],[122150.184,488463.553],[122150.403,488463.609],[122150.617,488463.68],[122150.826,488463.765],[122151.029,488463.864],[122151.225,488463.976],[122151.413,488464.101],[122151.593,488464.238],[122151.762,488464.387],[122151.921,488464.547],[122152.07,488464.717],[122152.206,488464.897],[122152.33,488465.086],[122152.442,488465.282],[122152.54,488465.486],[122152.624,488465.695],[122152.694,488465.91],[122152.749,488466.129],[122152.79,488466.351],[122152.816,488466.575],[122153.979,488467.423],[122156.2,488464.376],[122156.268,488464.426],[122157.391,488462.897],[122158.52,488463.688],[122158.699,488463.43],[122162.641,488466.19],[122162.461,488466.447],[122165.661,488468.687],[122163.033,488472.517],[122161.55,488474.677],[122164.76,488477.026],[122162.651,488480.014],[122158.631,488485.707]]]]}},\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/351","title":"351","objectId":351}},"objectId":351,"straatnaam":"C. van Eesterenlaan","huisnummer":null,"huisletter":null,"huisnummertoevoeging":"216-228","huisnummeraanduiding":null,"eigendom":"Appartementsrecht","bagPandIds":["0363100012138540"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[124380.478,487175.389],[124380.349,487191.074],[124388.751,487191.137],[124391.398,487171.931],[124403.989,487172.046],[124405.581,487172.043],[124405.747,487149.49],[124403.928,487149.48],[124404.01,487136.608],[124404.012,487136.293],[124404.014,487135.978],[124420.948,487136.074],[124420.947,487136.294],[124420.788,487136.29],[124420.69,487142.899],[124420.938,487142.904],[124420.533,487201.618],[124420.332,487201.617],[124420.324,487201.371],[124417.971,487201.231],[124417.966,487201.378],[124401.347,487201.283],[124401.376,487197.025],[124401.379,487196.675],[124401.4,487193.585],[124399.418,487193.834],[124388.38,487193.829],[124388.517,487192.837],[124380.328,487192.771],[124380.299,487193.825],[124378.818,487193.824],[124378.817,487194.174],[124372.918,487194.129],[124366.818,487194.083],[124366.822,487193.533],[124366.841,487191.083],[124367.262,487135.698],[124382.06,487135.811],[124381.957,487149.349],[124380.657,487149.341],[124380.478,487175.389]]]]}},\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/354","title":"354","objectId":354}},"objectId":354,"straatnaam":"Cruquiusweg","huisnummer":11,"huisletter":null,"huisnummertoevoeging":null,"huisnummeraanduiding":null,"eigendom":"Volle eigendom","bagPandIds":["0363100012221103"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[124369.388,486846.529],[124363.358,486846.5],[124363.37,486843.974],[124369.4,486844.002],[124369.388,486846.529]]]]}},\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/355","title":"355","objectId":355}},"objectId":355,"straatnaam":"Cruquiusweg","huisnummer":84,"huisletter":null,"huisnummertoevoeging":null,"huisnummeraanduiding":null,"eigendom":"Volle eigendom","bagPandIds":["0363100012120937"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[125080.79,486778.288],[125114.398,486778.474],[125114.34,486788.972],[125114.304,486795.406],[125116.722,486795.419],[125116.66,486807.189],[125114.239,486807.176],[125114.189,486816.13],[125107.008,486816.095],[125106.959,486826.519],[125101.01,486826.497],[125101.01,486826.607],[125099.83,486827.263],[125097.748,486827.256],[125096.579,486826.581],[125096.579,486826.481],[125087.62,486826.449],[125087.67,486815.709],[125089.213,486815.718],[125089.337,486793.385],[125087.707,486793.376],[125087.739,486787.598],[125080.739,486787.559],[125080.79,486778.288]]]]}},\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/357","title":"357","objectId":357}},"objectId":357,"straatnaam":"Danie Theronstraat","huisnummer":2,"huisletter":null,"huisnummertoevoeging":null,"huisnummeraanduiding":null,"eigendom":"Volle eigendom","bagPandIds":["0363100012070259"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[122881.103,485087.381],[122881.16,485087.628],[122881.019,485087.669],[122880.924,485087.82],[122881.895,485092.088],[122877.759,485093.029],[122877.733,485093.035],[122871.63,485094.41],[122869.128,485083.668],[122867.191,485075.037],[122863.009,485075.971],[122862.006,485071.483],[122866.173,485070.537],[122865.785,485068.824],[122860.543,485070.01],[122859.212,485064.067],[122868.601,485061.96],[122868.771,485062.717],[122869.939,485067.927],[122871.814,485067.5],[122871.861,485067.701],[122872.206,485069.166],[122878.239,485067.799],[122886.62,485065.89],[122892.666,485064.52],[122892.383,485063.12],[122892.328,485062.849],[122894.136,485062.455],[122894.11,485062.34],[122898.302,485061.365],[122898.705,485063.158],[122900.827,485072.585],[122901.969,485077.66],[122902.022,485077.648],[122904.135,485087.035],[122904.08,485087.039],[122893.549,485089.439],[122891.516,485080.497],[122882.819,485082.482],[122883.823,485086.8],[122881.103,485087.381]]]]}},\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/359","title":"359","objectId":359}},"objectId":359,"straatnaam":"Dapperplein","huisnummer":34,"huisletter":null,"huisnummertoevoeging":null,"huisnummeraanduiding":null,"eigendom":"Appartementsrecht","bagPandIds":["0363100012158693"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[123675.081,486148.499],[123671.23,486147.18],[123660.919,486143.648],[123658.08,486142.676],[123659.643,486138.212],[123662.29,486130.652],[123674.08,486134.779],[123673.869,486138.985],[123674.407,486143.919],[123675.179,486148.482],[123675.081,486148.499]]]]}},\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/360","title":"360","objectId":360}},"objectId":360,"straatnaam":"Dapperplein","huisnummer":36,"huisletter":null,"huisnummertoevoeging":null,"huisnummeraanduiding":null,"eigendom":"Appartementsrecht","bagPandIds":["0363100012084765"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[123674.299,48

In [47]:
info_municipal = response.json()
info_municipal

{'_embedded': {'gebouwobjecten': [{'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/339',
      'title': '339',
      'objectId': 339}},
    'objectId': 339,
    'straatnaam': 'Aldebaranplein',
    'huisnummer': None,
    'huisletter': None,
    'huisnummertoevoeging': '2-4',
    'huisnummeraanduiding': None,
    'eigendom': 'Volle eigendom',
    'bagPandIds': ['0363100012062051'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[121372.063, 491634.878],
        [121376.943, 491631.063],
        [121391.455, 491649.607],
        [121387.537, 491652.685],
        [121388.672, 491654.135],
        [121384.725, 491657.232],
        [121384.585, 491657.342],
        [121372.794, 491642.255],
        [121370.318, 491644.189],
        [121369.794, 491643.519],
        [121367.381, 491645.403],
        [121367.311, 491645.314],
        [121356.804, 491631.911],
        [121354.963, 491633.353],
        [121353.057, 491630.911],
        [121345.047, 491637.161],
        [121344.739, 491636.744],
        [121344.487, 491636.933],
        [121344.22, 491637.099],
        [121343.94, 491637.241],
        [121343.647, 491637.359],
        [121343.346, 491637.45],
        [121343.038, 491637.514],
        [121342.726, 491637.552],
        [121342.411, 491637.561],
        [121342.097, 491637.544],
        [121341.786, 491637.499],
        [121341.479, 491637.427],
        [121341.181, 491637.328],
        [121340.892, 491637.204],
        [121340.614, 491637.055],
        [121340.352, 491636.882],
        [121340.105, 491636.687],
        [121339.876, 491636.471],
        [121339.667, 491636.235],
        [121339.479, 491635.983],
        [121339.314, 491635.715],
        [121339.177, 491635.442],
        [121339.063, 491635.157],
        [121338.974, 491634.865],
        [121338.91, 491634.565],
        [121338.872, 491634.262],
        [121338.86, 491633.956],
        [121338.874, 491633.65],
        [121338.914, 491633.347],
        [121338.979, 491633.048],
        [121339.07, 491632.756],
        [121339.185, 491632.472],
        [121339.323, 491632.2],
        [121339.485, 491631.94],
        [121339.668, 491631.695],
        [121339.871, 491631.466],
        [121340.093, 491631.255],
        [121340.332, 491631.064],
        [121339.992, 491630.698],
        [121342.306, 491628.89],
        [121347.98, 491624.439],
        [121346.066, 491621.962],
        [121347.903, 491620.525],
        [121337.409, 491607.093],
        [121337.345, 491607.011],
        [121339.732, 491605.125],
        [121339.22, 491604.471],
        [121341.687, 491602.541],
        [121329.884, 491587.454],
        [121329.964, 491587.405],
        [121333.962, 491584.252],
        [121335.121, 491585.719],
        [121339.042, 491582.627],
        [121353.539, 491601.144],
        [121348.668, 491604.965],
        [121359.789, 491619.185],
        [121360.875, 491620.573],
        [121372.063, 491634.878]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/340',
      'title': '340',
      'objectId': 340}},
    'objectId': 340,
    'straatnaam': 'Alkmaarstraat',
    'huisnummer': 10,
    'huisletter': None,
    'huisnummertoevoeging': None,
    'huisnummeraanduiding': None,
    'eigendom': 'Volle eigendom',
    'bagPandIds': ['0363100012097095'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[125358.8, 489748.605],
        [125358.96, 489748.99],
        [125348.446, 489754.175],
        [125345.13, 489755.81],
        [125344.271, 489754.052],
        [125343.876, 489754.343],
        [125339.47, 489757.59],
        [125339.943, 489758.582],
        [125340.33, 489758.46],
        [125340.45, 489758.84],
        [125333.55, 489760.85],
        [125334.23, 489762.28],
        [125334.34, 489762.21],
        [125334.59, 489762.53],
        [125327.53, 489767.72],
        [125327.454, 489767.742],
        [125323.269, 489768.929],
        [125321.72, 489763.87],
        [125320.38, 489764.28],
        [125318.76, 489759.39],
        [125318.08, 489759.62],
        [125316.6, 489755.16],
        [125319.023, 489754.365],
        [125316.579, 489749.53],
        [125315.0, 489750.32],
        [125310.809, 489744.89],
        [125315.526, 489741.236],
        [125315.65, 489741.14],
        [125316.31, 489741.94],
        [125320.36, 489738.829],
        [125320.98, 489739.63],
        [125325.05, 489736.52],
        [125325.69, 489737.27],
        [125327.04, 489736.11],
        [125326.84, 489735.87],
        [125331.19, 489732.07],
        [125331.92, 489732.16],
        [125333.13, 489733.55],
        [125335.809, 489731.17],
        [125336.5, 489731.96],
        [125339.42, 489729.38],
        [125340.11, 489730.16],
        [125346.85, 489725.729],
        [125350.23, 489730.86],
        [125351.244, 489730.358],
        [125353.55, 489734.3],
        [125352.95, 489734.66],
        [125355.4, 489738.04],
        [125354.84, 489738.46],
        [125357.96, 489743.79],
        [125357.03, 489744.34],
        [125357.268, 489744.917],
        [125357.282, 489744.951],
        [125357.966, 489746.608],
        [125358.8, 489748.605]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/341',
      'title': '341',
      'objectId': 341}},
    'objectId': 341,
    'straatnaam': 'Amstelkade',
    'huisnummer': 13,
    'huisletter': None,
    'huisnummertoevoeging': None,
    'huisnummeraanduiding': None,
    'eigendom': 'Volle eigendom',
    'bagPandIds': ['0363100012103599'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[122322.447, 484699.324],
        [122322.371, 484699.666],
        [122321.728, 484702.544],
        [122321.652, 484702.886],
        [122321.499, 484703.569],
        [122314.449, 484702.029],
        [122315.009, 484699.439],
        [122309.539, 484698.229],
        [122312.999, 484682.539],
        [122314.87, 484682.92],
        [122314.729, 484683.469],
        [122321.551, 484684.991],
        [122321.799, 484683.92],
        [122326.219, 484684.88],
        [122326.11, 484685.42],
        [122325.58, 484685.299],
        [122322.447, 484699.324]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/343',
      'title': '343',
      'objectId': 343}},
    'objectId': 343,
    'straatnaam': 'Berberisstraat',
    'huisnummer': 16,
    'huisletter': None,
    'huisnummertoevoeging': None,
    'huisnummeraanduiding': None,
    'eigendom': 'Volle eigendom',
    'bagPandIds': ['0363100012163016'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[122923.382, 489563.258],
        [122898.935, 489562.172],
        [122898.794, 489565.34],
        [122894.908, 489565.167],
        [122895.049, 489562.0],
        [122885.768, 489561.588],
        [122886.381, 489547.791],
        [122887.659, 489547.848],
        [122899.302, 489548.365],
        [122899.649, 489548.38],
        [122899.615, 489549.139],
        [122923.959, 489550.219],
        [122923.951, 489550.441],
        [122923.78, 489554.296],
        [122923.382, 489563.258]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/344',
      'title': '344',
      'objectId': 344}},
    'objectId': 344,
    'straatnaam': 'Bezaanjachtplein',
    'huisnummer': None,
    'huisletter': None,
    'huisnummertoevoeging': '243 t/m 251',
    'huisnummeraanduiding': None,
    'eigendom': 'Appartementsrecht',
    'bagPandIds': ['0363100012239467'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[123011.8, 491225.599],
        [122993.876, 491201.646],
        [123005.372, 491193.062],
        [123023.301, 491216.992],
        [123011.8, 491225.599]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/347',
      'title': '347',
      'objectId': 347}},
    'objectId': 347,
    'straatnaam': 'Brigantijnkade',
    'huisnummer': 53,
    'huisletter': None,
    'huisnummertoevoeging': None,
    'huisnummeraanduiding': None,
    'eigendom': 'Appartementsrecht',
    'bagPandIds': ['0363100012207608'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[127771.587, 486210.758],
        [127756.742, 486223.783],
        [127746.272, 486211.847],
        [127746.218, 486211.786],
        [127776.941, 486165.789],
        [127782.357, 486157.679],
        [127782.368, 486157.663],
        [127782.522, 486157.433],
        [127782.612, 486157.497],
        [127782.593, 486157.529],
        [127799.745, 486177.085],
        [127799.525, 486177.278],
        [127799.54, 486177.295],
        [127790.575, 486185.194],
        [127794.989, 486190.224],
        [127771.587, 486210.758]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/349',
      'title': '349',
      'objectId': 349}},
    'objectId': 349,
    'straatnaam': 'Buiksloterweg',
    'huisnummer': 5,
    'huisletter': None,
    'huisnummertoevoeging': None,
    'huisnummeraanduiding': None,
    'eigendom': 'Volle eigendom',
    'bagPandIds': ['0363100012164355'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[122048.585, 488407.027],
        [122050.127, 488404.884],
        [122046.637, 488402.372],
        [122050.557, 488396.926],
        [122051.003, 488397.247],
        [122052.16, 488395.64],
        [122055.932, 488398.355],
        [122054.759, 488399.951],
        [122068.799, 488410.058],
        [122069.955, 488408.451],
        [122073.704, 488411.15],
        [122072.549, 488412.759],
        [122072.979, 488413.079],
        [122069.07, 488418.519],
        [122065.583, 488416.013],
        [122064.042, 488418.157],
        [122048.585, 488407.027]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/350',
      'title': '350',
      'objectId': 350}},
    'objectId': 350,
    'straatnaam': 'Buiksloterweg',
    'huisnummer': 7,
    'huisletter': None,
    'huisnummertoevoeging': None,
    'huisnummeraanduiding': None,
    'eigendom': 'Volle eigendom',
    'bagPandIds': ['0363100012066897'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[122158.631, 488485.707],
        [122161.47, 488487.756],
        [122157.198, 488493.676],
        [122151.491, 488489.555],
        [122150.466, 488490.974],
        [122150.643, 488491.113],
        [122150.811, 488491.265],
        [122150.968, 488491.427],
        [122151.113, 488491.6],
        [122151.247, 488491.781],
        [122151.368, 488491.972],
        [122151.475, 488492.17],
        [122151.57, 488492.376],
        [122151.65, 488492.587],
        [122151.715, 488492.803],
        [122151.766, 488493.022],
        [122151.802, 488493.245],
        [122151.822, 488493.47],
        [122151.828, 488493.696],
        [122151.818, 488493.921],
        [122151.793, 488494.146],
        [122151.753, 488494.368],
        [122151.698, 488494.587],
        [122151.628, 488494.801],
        [122151.544, 488495.011],
        [122151.445, 488495.214],
        [122151.334, 488495.41],
        [122151.209, 488495.598],
        [122151.072, 488495.778],
        [122150.923, 488495.947],
        [122150.763, 488496.106],
        [122150.593, 488496.254],
        [122150.412, 488496.39],
        [122150.224, 488496.514],
        [122150.027, 488496.624],
        [122149.823, 488496.721],
        [122149.613, 488496.804],
        [122149.398, 488496.873],
        [122149.179, 488496.927],
        [122147.919, 488498.696],
        [122147.352, 488498.558],
        [122146.788, 488498.406],
        [122146.229, 488498.24],
        [122145.674, 488498.06],
        [122145.123, 488497.865],
        [122144.578, 488497.657],
        [122144.038, 488497.435],
        [122143.504, 488497.2],
        [122142.976, 488496.951],
        [122142.455, 488496.689],
        [122141.94, 488496.414],
        [122141.823, 488496.326],
        [122141.716, 488496.226],
        [122141.619, 488496.116],
        [122141.534, 488495.997],
        [122141.461, 488495.87],
        [122141.401, 488495.737],
        [122141.354, 488495.598],
        [122141.322, 488495.455],
        [122141.305, 488495.31],
        [122141.302, 488495.163],
        [122141.313, 488495.017],
        [122141.339, 488494.873],
        [122141.38, 488494.733],
        [122141.434, 488494.597],
        [122141.502, 488494.467],
        [122141.583, 488494.345],
        [122141.675, 488494.231],
        [122139.006, 488492.305],
        [122138.927, 488492.43],
        [122138.836, 488492.547],
        [122138.735, 488492.655],
        [122138.623, 488492.751],
        [122138.502, 488492.836],
        [122138.373, 488492.909],
        [122138.237, 488492.969],
        [122138.097, 488493.015],
        [122137.952, 488493.046],
        [122137.805, 488493.064],
        [122137.657, 488493.066],
        [122137.509, 488493.054],
        [122137.364, 488493.028],
        [122137.222, 488492.987],
        [122137.084, 488492.932],
        [122136.953, 488492.864],
        [122136.829, 488492.783],
        [122136.406, 488492.377],
        [122135.993, 488491.962],
        [122135.59, 488491.536],
        [122135.198, 488491.1],
        [122134.817, 488490.655],
        [122134.447, 488490.201],
        [122134.088, 488489.738],
        [122133.74, 488489.266],
        [122133.404, 488488.786],
        [122133.08, 488488.298],
        [122132.768, 488487.802],
        [122132.873, 488487.655],
        [122134.021, 488486.053],
        [122133.999, 488485.829],
        [122133.993, 488485.604],
        [122134.001, 488485.379],
        [122134.026, 488485.155],
        [122134.065, 488484.933],
        [122134.119, 488484.714],
        [122134.189, 488484.5],
        [122134.272, 488484.291],
        [122134.37, 488484.088],
        [122134.481, 488483.892],
        [122134.605, 488483.704],
        [122134.742, 488483.525],
        [122134.89, 488483.356],
        [122135.05, 488483.197],
        [122135.221, 488483.05],
        [122135.4, 488482.914],
        [122135.589, 488482.791],
        [122135.786, 488482.681],
        [122135.989, 488482.585],
        [122136.199, 488482.503],
        [122136.414, 488482.435],
        [122136.633, 488482.383],
        [122136.855, 488482.345],
        [122137.079, 488482.322],
        [122137.304, 488482.315],
        [122137.529, 488482.323],
        [122137.753, 488482.346],
        [122137.975, 488482.385],
        [122138.194, 488482.438],
        [122138.408, 488482.506],
        [122138.618, 488482.589],
        [122138.821, 488482.686],
        [122139.018, 488482.796],
        [122139.206, 488482.92],
        [122140.217, 488481.516],
        [122140.153, 488481.469],
        [122144.46, 488475.566],
        [122146.96, 488477.356],
        [122149.104, 488474.489],
        [122147.948, 488473.63],
        [122147.733, 488473.687],
        [122147.516, 488473.73],
        [122147.295, 488473.758],
        [122147.074, 488473.771],
        [122146.852, 488473.77],
        [122146.631, 488473.754],
        [122146.411, 488473.724],
        [122146.194, 488473.679],
        [122145.98, 488473.619],
        [122145.77, 488473.546],
        [122145.566, 488473.459],
        [122145.368, 488473.358],
        [122145.178, 488473.245],
        [122144.995, 488473.119],
        [122144.851, 488473.006],
        [122144.679, 488472.854],
        [122144.519, 488472.69],
        [122144.369, 488472.515],
        [122144.233, 488472.331],
        [122144.109, 488472.138],
        [122143.998, 488471.937],
        [122143.902, 488471.729],
        [122143.822, 488471.423],
        [122143.756, 488471.114],
        [122143.706, 488470.802],
        [122143.671, 488470.488],
        [122143.651, 488470.173],
        [122143.646, 488469.857],
        [122143.656, 488469.541],
        [122143.682, 488469.226],
        [122143.723, 488468.913],
        [122143.78, 488468.602],
        [122143.851, 488468.294],
        [122143.937, 488467.99],
        [122144.037, 488467.69],
        [122144.152, 488467.396],
        [122144.281, 488467.107],
        [122144.424, 488466.826],
        [122144.581, 488466.551],
        [122144.75, 488466.284],
        [122144.932, 488466.026],
        [122145.127, 488465.777],
        [122145.333, 488465.538],
        [122145.551, 488465.309],
        [122145.779, 488465.09],
        [122146.018, 488464.883],
        [122146.267, 488464.688],
        [122146.524, 488464.505],
        [122146.79, 488464.335],
        [122147.065, 488464.178],
        [122147.346, 488464.034],
        [122147.634, 488463.904],
        [122147.928, 488463.788],
        [122148.227, 488463.687],
        [122148.531, 488463.6],
        [122148.839, 488463.528],
        [122149.062, 488463.494],
        [122149.287, 488463.476],
        [122149.513, 488463.472],
        [122149.738, 488463.484],
        [122149.962, 488463.511],
        [122150.184, 488463.553],
        [122150.403, 488463.609],
        [122150.617, 488463.68],
        [122150.826, 488463.765],
        [122151.029, 488463.864],
        [122151.225, 488463.976],
        [122151.413, 488464.101],
        [122151.593, 488464.238],
        [122151.762, 488464.387],
        [122151.921, 488464.547],
        [122152.07, 488464.717],
        [122152.206, 488464.897],
        [122152.33, 488465.086],
        [122152.442, 488465.282],
        [122152.54, 488465.486],
        [122152.624, 488465.695],
        [122152.694, 488465.91],
        [122152.749, 488466.129],
        [122152.79, 488466.351],
        [122152.816, 488466.575],
        [122153.979, 488467.423],
        [122156.2, 488464.376],
        [122156.268, 488464.426],
        [122157.391, 488462.897],
        [122158.52, 488463.688],
        [122158.699, 488463.43],
        [122162.641, 488466.19],
        [122162.461, 488466.447],
        [122165.661, 488468.687],
        [122163.033, 488472.517],
        [122161.55, 488474.677],
        [122164.76, 488477.026],
        [122162.651, 488480.014],
        [122158.631, 488485.707]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/351',
      'title': '351',
      'objectId': 351}},
    'objectId': 351,
    'straatnaam': 'C. van Eesterenlaan',
    'huisnummer': None,
    'huisletter': None,
    'huisnummertoevoeging': '216-228',
    'huisnummeraanduiding': None,
    'eigendom': 'Appartementsrecht',
    'bagPandIds': ['0363100012138540'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[124380.478, 487175.389],
        [124380.349, 487191.074],
        [124388.751, 487191.137],
        [124391.398, 487171.931],
        [124403.989, 487172.046],
        [124405.581, 487172.043],
        [124405.747, 487149.49],
        [124403.928, 487149.48],

In [48]:
type(info_municipal)

dict

In [49]:
info_municipal.keys()

dict_keys(['_embedded', '_links', 'page'])

In [50]:
info_municipal['_embedded'].keys()

dict_keys(['gebouwobjecten'])

In [51]:
info_municipal['_embedded']['gebouwobjecten'][0].keys()

dict_keys(['_links', 'objectId', 'straatnaam', 'huisnummer', 'huisletter', 'huisnummertoevoeging', 'huisnummeraanduiding', 'eigendom', 'bagPandIds', 'geometrie'])

#### Finding

**No postcode**

### Building -gebouwobjecten

#### Endpoint

In [58]:
url_buildingobject="https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten"
response_buildingobject = requests.get(url_buildingobject)
print(response_buildingobject.status_code)

200

#### Response

In [59]:
info_buildingobject = response_buildingobject.json()
info_buildingobject

{'_embedded': {'gebouwobjecten': [{'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/339',
      'title': '339',
      'objectId': 339}},
    'objectId': 339,
    'straatnaam': 'Aldebaranplein',
    'huisnummer': None,
    'huisletter': None,
    'huisnummertoevoeging': '2-4',
    'huisnummeraanduiding': None,
    'eigendom': 'Volle eigendom',
    'bagPandIds': ['0363100012062051'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[121372.063, 491634.878],
        [121376.943, 491631.063],
        [121391.455, 491649.607],
        [121387.537, 491652.685],
        [121388.672, 491654.135],
        [121384.725, 491657.232],
        [121384.585, 491657.342],
        [121372.794, 491642.255],
        [121370.318, 491644.189],
        [121369.794, 491643.519],
        [121367.381, 491645.403],
        [121367.311, 491645.314],
        [121356.804, 491631.911],
        [121354.963, 491633.353],
        [121353.057, 491630.911],
        [121345.047, 491637.161],
        [121344.739, 491636.744],
        [121344.487, 491636.933],
        [121344.22, 491637.099],
        [121343.94, 491637.241],
        [121343.647, 491637.359],
        [121343.346, 491637.45],
        [121343.038, 491637.514],
        [121342.726, 491637.552],
        [121342.411, 491637.561],
        [121342.097, 491637.544],
        [121341.786, 491637.499],
        [121341.479, 491637.427],
        [121341.181, 491637.328],
        [121340.892, 491637.204],
        [121340.614, 491637.055],
        [121340.352, 491636.882],
        [121340.105, 491636.687],
        [121339.876, 491636.471],
        [121339.667, 491636.235],
        [121339.479, 491635.983],
        [121339.314, 491635.715],
        [121339.177, 491635.442],
        [121339.063, 491635.157],
        [121338.974, 491634.865],
        [121338.91, 491634.565],
        [121338.872, 491634.262],
        [121338.86, 491633.956],
        [121338.874, 491633.65],
        [121338.914, 491633.347],
        [121338.979, 491633.048],
        [121339.07, 491632.756],
        [121339.185, 491632.472],
        [121339.323, 491632.2],
        [121339.485, 491631.94],
        [121339.668, 491631.695],
        [121339.871, 491631.466],
        [121340.093, 491631.255],
        [121340.332, 491631.064],
        [121339.992, 491630.698],
        [121342.306, 491628.89],
        [121347.98, 491624.439],
        [121346.066, 491621.962],
        [121347.903, 491620.525],
        [121337.409, 491607.093],
        [121337.345, 491607.011],
        [121339.732, 491605.125],
        [121339.22, 491604.471],
        [121341.687, 491602.541],
        [121329.884, 491587.454],
        [121329.964, 491587.405],
        [121333.962, 491584.252],
        [121335.121, 491585.719],
        [121339.042, 491582.627],
        [121353.539, 491601.144],
        [121348.668, 491604.965],
        [121359.789, 491619.185],
        [121360.875, 491620.573],
        [121372.063, 491634.878]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/340',
      'title': '340',
      'objectId': 340}},
    'objectId': 340,
    'straatnaam': 'Alkmaarstraat',
    'huisnummer': 10,
    'huisletter': None,
    'huisnummertoevoeging': None,
    'huisnummeraanduiding': None,
    'eigendom': 'Volle eigendom',
    'bagPandIds': ['0363100012097095'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[125358.8, 489748.605],
        [125358.96, 489748.99],
        [125348.446, 489754.175],
        [125345.13, 489755.81],
        [125344.271, 489754.052],
        [125343.876, 489754.343],
        [125339.47, 489757.59],
        [125339.943, 489758.582],
        [125340.33, 489758.46],
        [125340.45, 489758.84],
        [125333.55, 489760.85],
        [125334.23, 489762.28],
        [125334.34, 489762.21],
        [125334.59, 489762.53],
        [125327.53, 489767.72],
        [125327.454, 489767.742],
        [125323.269, 489768.929],
        [125321.72, 489763.87],
        [125320.38, 489764.28],
        [125318.76, 489759.39],
        [125318.08, 489759.62],
        [125316.6, 489755.16],
        [125319.023, 489754.365],
        [125316.579, 489749.53],
        [125315.0, 489750.32],
        [125310.809, 489744.89],
        [125315.526, 489741.236],
        [125315.65, 489741.14],
        [125316.31, 489741.94],
        [125320.36, 489738.829],
        [125320.98, 489739.63],
        [125325.05, 489736.52],
        [125325.69, 489737.27],
        [125327.04, 489736.11],
        [125326.84, 489735.87],
        [125331.19, 489732.07],
        [125331.92, 489732.16],
        [125333.13, 489733.55],
        [125335.809, 489731.17],
        [125336.5, 489731.96],
        [125339.42, 489729.38],
        [125340.11, 489730.16],
        [125346.85, 489725.729],
        [125350.23, 489730.86],
        [125351.244, 489730.358],
        [125353.55, 489734.3],
        [125352.95, 489734.66],
        [125355.4, 489738.04],
        [125354.84, 489738.46],
        [125357.96, 489743.79],
        [125357.03, 489744.34],
        [125357.268, 489744.917],
        [125357.282, 489744.951],
        [125357.966, 489746.608],
        [125358.8, 489748.605]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/341',
      'title': '341',
      'objectId': 341}},
    'objectId': 341,
    'straatnaam': 'Amstelkade',
    'huisnummer': 13,
    'huisletter': None,
    'huisnummertoevoeging': None,
    'huisnummeraanduiding': None,
    'eigendom': 'Volle eigendom',
    'bagPandIds': ['0363100012103599'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[122322.447, 484699.324],
        [122322.371, 484699.666],
        [122321.728, 484702.544],
        [122321.652, 484702.886],
        [122321.499, 484703.569],
        [122314.449, 484702.029],
        [122315.009, 484699.439],
        [122309.539, 484698.229],
        [122312.999, 484682.539],
        [122314.87, 484682.92],
        [122314.729, 484683.469],
        [122321.551, 484684.991],
        [122321.799, 484683.92],
        [122326.219, 484684.88],
        [122326.11, 484685.42],
        [122325.58, 484685.299],
        [122322.447, 484699.324]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/343',
      'title': '343',
      'objectId': 343}},
    'objectId': 343,
    'straatnaam': 'Berberisstraat',
    'huisnummer': 16,
    'huisletter': None,
    'huisnummertoevoeging': None,
    'huisnummeraanduiding': None,
    'eigendom': 'Volle eigendom',
    'bagPandIds': ['0363100012163016'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[122923.382, 489563.258],
        [122898.935, 489562.172],
        [122898.794, 489565.34],
        [122894.908, 489565.167],
        [122895.049, 489562.0],
        [122885.768, 489561.588],
        [122886.381, 489547.791],
        [122887.659, 489547.848],
        [122899.302, 489548.365],
        [122899.649, 489548.38],
        [122899.615, 489549.139],
        [122923.959, 489550.219],
        [122923.951, 489550.441],
        [122923.78, 489554.296],
        [122923.382, 489563.258]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/344',
      'title': '344',
      'objectId': 344}},
    'objectId': 344,
    'straatnaam': 'Bezaanjachtplein',
    'huisnummer': None,
    'huisletter': None,
    'huisnummertoevoeging': '243 t/m 251',
    'huisnummeraanduiding': None,
    'eigendom': 'Appartementsrecht',
    'bagPandIds': ['0363100012239467'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[123011.8, 491225.599],
        [122993.876, 491201.646],
        [123005.372, 491193.062],
        [123023.301, 491216.992],
        [123011.8, 491225.599]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/347',
      'title': '347',
      'objectId': 347}},
    'objectId': 347,
    'straatnaam': 'Brigantijnkade',
    'huisnummer': 53,
    'huisletter': None,
    'huisnummertoevoeging': None,
    'huisnummeraanduiding': None,
    'eigendom': 'Appartementsrecht',
    'bagPandIds': ['0363100012207608'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[127771.587, 486210.758],
        [127756.742, 486223.783],
        [127746.272, 486211.847],
        [127746.218, 486211.786],
        [127776.941, 486165.789],
        [127782.357, 486157.679],
        [127782.368, 486157.663],
        [127782.522, 486157.433],
        [127782.612, 486157.497],
        [127782.593, 486157.529],
        [127799.745, 486177.085],
        [127799.525, 486177.278],
        [127799.54, 486177.295],
        [127790.575, 486185.194],
        [127794.989, 486190.224],
        [127771.587, 486210.758]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/349',
      'title': '349',
      'objectId': 349}},
    'objectId': 349,
    'straatnaam': 'Buiksloterweg',
    'huisnummer': 5,
    'huisletter': None,
    'huisnummertoevoeging': None,
    'huisnummeraanduiding': None,
    'eigendom': 'Volle eigendom',
    'bagPandIds': ['0363100012164355'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[122048.585, 488407.027],
        [122050.127, 488404.884],
        [122046.637, 488402.372],
        [122050.557, 488396.926],
        [122051.003, 488397.247],
        [122052.16, 488395.64],
        [122055.932, 488398.355],
        [122054.759, 488399.951],
        [122068.799, 488410.058],
        [122069.955, 488408.451],
        [122073.704, 488411.15],
        [122072.549, 488412.759],
        [122072.979, 488413.079],
        [122069.07, 488418.519],
        [122065.583, 488416.013],
        [122064.042, 488418.157],
        [122048.585, 488407.027]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/350',
      'title': '350',
      'objectId': 350}},
    'objectId': 350,
    'straatnaam': 'Buiksloterweg',
    'huisnummer': 7,
    'huisletter': None,
    'huisnummertoevoeging': None,
    'huisnummeraanduiding': None,
    'eigendom': 'Volle eigendom',
    'bagPandIds': ['0363100012066897'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[122158.631, 488485.707],
        [122161.47, 488487.756],
        [122157.198, 488493.676],
        [122151.491, 488489.555],
        [122150.466, 488490.974],
        [122150.643, 488491.113],
        [122150.811, 488491.265],
        [122150.968, 488491.427],
        [122151.113, 488491.6],
        [122151.247, 488491.781],
        [122151.368, 488491.972],
        [122151.475, 488492.17],
        [122151.57, 488492.376],
        [122151.65, 488492.587],
        [122151.715, 488492.803],
        [122151.766, 488493.022],
        [122151.802, 488493.245],
        [122151.822, 488493.47],
        [122151.828, 488493.696],
        [122151.818, 488493.921],
        [122151.793, 488494.146],
        [122151.753, 488494.368],
        [122151.698, 488494.587],
        [122151.628, 488494.801],
        [122151.544, 488495.011],
        [122151.445, 488495.214],
        [122151.334, 488495.41],
        [122151.209, 488495.598],
        [122151.072, 488495.778],
        [122150.923, 488495.947],
        [122150.763, 488496.106],
        [122150.593, 488496.254],
        [122150.412, 488496.39],
        [122150.224, 488496.514],
        [122150.027, 488496.624],
        [122149.823, 488496.721],
        [122149.613, 488496.804],
        [122149.398, 488496.873],
        [122149.179, 488496.927],
        [122147.919, 488498.696],
        [122147.352, 488498.558],
        [122146.788, 488498.406],
        [122146.229, 488498.24],
        [122145.674, 488498.06],
        [122145.123, 488497.865],
        [122144.578, 488497.657],
        [122144.038, 488497.435],
        [122143.504, 488497.2],
        [122142.976, 488496.951],
        [122142.455, 488496.689],
        [122141.94, 488496.414],
        [122141.823, 488496.326],
        [122141.716, 488496.226],
        [122141.619, 488496.116],
        [122141.534, 488495.997],
        [122141.461, 488495.87],
        [122141.401, 488495.737],
        [122141.354, 488495.598],
        [122141.322, 488495.455],
        [122141.305, 488495.31],
        [122141.302, 488495.163],
        [122141.313, 488495.017],
        [122141.339, 488494.873],
        [122141.38, 488494.733],
        [122141.434, 488494.597],
        [122141.502, 488494.467],
        [122141.583, 488494.345],
        [122141.675, 488494.231],
        [122139.006, 488492.305],
        [122138.927, 488492.43],
        [122138.836, 488492.547],
        [122138.735, 488492.655],
        [122138.623, 488492.751],
        [122138.502, 488492.836],
        [122138.373, 488492.909],
        [122138.237, 488492.969],
        [122138.097, 488493.015],
        [122137.952, 488493.046],
        [122137.805, 488493.064],
        [122137.657, 488493.066],
        [122137.509, 488493.054],
        [122137.364, 488493.028],
        [122137.222, 488492.987],
        [122137.084, 488492.932],
        [122136.953, 488492.864],
        [122136.829, 488492.783],
        [122136.406, 488492.377],
        [122135.993, 488491.962],
        [122135.59, 488491.536],
        [122135.198, 488491.1],
        [122134.817, 488490.655],
        [122134.447, 488490.201],
        [122134.088, 488489.738],
        [122133.74, 488489.266],
        [122133.404, 488488.786],
        [122133.08, 488488.298],
        [122132.768, 488487.802],
        [122132.873, 488487.655],
        [122134.021, 488486.053],
        [122133.999, 488485.829],
        [122133.993, 488485.604],
        [122134.001, 488485.379],
        [122134.026, 488485.155],
        [122134.065, 488484.933],
        [122134.119, 488484.714],
        [122134.189, 488484.5],
        [122134.272, 488484.291],
        [122134.37, 488484.088],
        [122134.481, 488483.892],
        [122134.605, 488483.704],
        [122134.742, 488483.525],
        [122134.89, 488483.356],
        [122135.05, 488483.197],
        [122135.221, 488483.05],
        [122135.4, 488482.914],
        [122135.589, 488482.791],
        [122135.786, 488482.681],
        [122135.989, 488482.585],
        [122136.199, 488482.503],
        [122136.414, 488482.435],
        [122136.633, 488482.383],
        [122136.855, 488482.345],
        [122137.079, 488482.322],
        [122137.304, 488482.315],
        [122137.529, 488482.323],
        [122137.753, 488482.346],
        [122137.975, 488482.385],
        [122138.194, 488482.438],
        [122138.408, 488482.506],
        [122138.618, 488482.589],
        [122138.821, 488482.686],
        [122139.018, 488482.796],
        [122139.206, 488482.92],
        [122140.217, 488481.516],
        [122140.153, 488481.469],
        [122144.46, 488475.566],
        [122146.96, 488477.356],
        [122149.104, 488474.489],
        [122147.948, 488473.63],
        [122147.733, 488473.687],
        [122147.516, 488473.73],
        [122147.295, 488473.758],
        [122147.074, 488473.771],
        [122146.852, 488473.77],
        [122146.631, 488473.754],
        [122146.411, 488473.724],
        [122146.194, 488473.679],
        [122145.98, 488473.619],
        [122145.77, 488473.546],
        [122145.566, 488473.459],
        [122145.368, 488473.358],
        [122145.178, 488473.245],
        [122144.995, 488473.119],
        [122144.851, 488473.006],
        [122144.679, 488472.854],
        [122144.519, 488472.69],
        [122144.369, 488472.515],
        [122144.233, 488472.331],
        [122144.109, 488472.138],
        [122143.998, 488471.937],
        [122143.902, 488471.729],
        [122143.822, 488471.423],
        [122143.756, 488471.114],
        [122143.706, 488470.802],
        [122143.671, 488470.488],
        [122143.651, 488470.173],
        [122143.646, 488469.857],
        [122143.656, 488469.541],
        [122143.682, 488469.226],
        [122143.723, 488468.913],
        [122143.78, 488468.602],
        [122143.851, 488468.294],
        [122143.937, 488467.99],
        [122144.037, 488467.69],
        [122144.152, 488467.396],
        [122144.281, 488467.107],
        [122144.424, 488466.826],
        [122144.581, 488466.551],
        [122144.75, 488466.284],
        [122144.932, 488466.026],
        [122145.127, 488465.777],
        [122145.333, 488465.538],
        [122145.551, 488465.309],
        [122145.779, 488465.09],
        [122146.018, 488464.883],
        [122146.267, 488464.688],
        [122146.524, 488464.505],
        [122146.79, 488464.335],
        [122147.065, 488464.178],
        [122147.346, 488464.034],
        [122147.634, 488463.904],
        [122147.928, 488463.788],
        [122148.227, 488463.687],
        [122148.531, 488463.6],
        [122148.839, 488463.528],
        [122149.062, 488463.494],
        [122149.287, 488463.476],
        [122149.513, 488463.472],
        [122149.738, 488463.484],
        [122149.962, 488463.511],
        [122150.184, 488463.553],
        [122150.403, 488463.609],
        [122150.617, 488463.68],
        [122150.826, 488463.765],
        [122151.029, 488463.864],
        [122151.225, 488463.976],
        [122151.413, 488464.101],
        [122151.593, 488464.238],
        [122151.762, 488464.387],
        [122151.921, 488464.547],
        [122152.07, 488464.717],
        [122152.206, 488464.897],
        [122152.33, 488465.086],
        [122152.442, 488465.282],
        [122152.54, 488465.486],
        [122152.624, 488465.695],
        [122152.694, 488465.91],
        [122152.749, 488466.129],
        [122152.79, 488466.351],
        [122152.816, 488466.575],
        [122153.979, 488467.423],
        [122156.2, 488464.376],
        [122156.268, 488464.426],
        [122157.391, 488462.897],
        [122158.52, 488463.688],
        [122158.699, 488463.43],
        [122162.641, 488466.19],
        [122162.461, 488466.447],
        [122165.661, 488468.687],
        [122163.033, 488472.517],
        [122161.55, 488474.677],
        [122164.76, 488477.026],
        [122162.651, 488480.014],
        [122158.631, 488485.707]]]]}},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/351',
      'title': '351',
      'objectId': 351}},
    'objectId': 351,
    'straatnaam': 'C. van Eesterenlaan',
    'huisnummer': None,
    'huisletter': None,
    'huisnummertoevoeging': '216-228',
    'huisnummeraanduiding': None,
    'eigendom': 'Appartementsrecht',
    'bagPandIds': ['0363100012138540'],
    'geometrie': {'type': 'MultiPolygon',
     'coordinates': [[[[124380.478, 487175.389],
        [124380.349, 487191.074],
        [124388.751, 487191.137],
        [124391.398, 487171.931],
        [124403.989, 487172.046],
        [124405.581, 487172.043],
        [124405.747, 487149.49],
        [124403.928, 487149.48],

In [60]:
info_buildingobject.keys()

dict_keys(['_embedded', '_links', 'page'])

In [65]:
info_buildingobject['_embedded']['gebouwobjecten'][0]

{'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1',
  'self': {'href': 'https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/339',
   'title': '339',
   'objectId': 339}},
 'objectId': 339,
 'straatnaam': 'Aldebaranplein',
 'huisnummer': None,
 'huisletter': None,
 'huisnummertoevoeging': '2-4',
 'huisnummeraanduiding': None,
 'eigendom': 'Volle eigendom',
 'bagPandIds': ['0363100012062051'],
 'geometrie': {'type': 'MultiPolygon',
  'coordinates': [[[[121372.063, 491634.878],
     [121376.943, 491631.063],
     [121391.455, 491649.607],
     [121387.537, 491652.685],
     [121388.672, 491654.135],
     [121384.725, 491657.232],
     [121384.585, 491657.342],
     [121372.794, 491642.255],
     [121370.318, 491644.189],
     [121369.794, 491643.519],
     [121367.381, 491645.403],
     [121367.311, 491645.314],
     [121356.804, 491631.911],
     [121354.963, 491633.353],
     [121353.057, 491630.911],
     [121345.047, 491637.161],
     [121344.739, 491636.744],
     [121344.487, 491636.933],
     [121344.22, 491637.099],
     [121343.94, 491637.241],
     [121343.647, 491637.359],
     [121343.346, 491637.45],
     [121343.038, 491637.514],
     [121342.726, 491637.552],
     [121342.411, 491637.561],
     [121342.097, 491637.544],
     [121341.786, 491637.499],
     [121341.479, 491637.427],
     [121341.181, 491637.328],
     [121340.892, 491637.204],
     [121340.614, 491637.055],
     [121340.352, 491636.882],
     [121340.105, 491636.687],
     [121339.876, 491636.471],
     [121339.667, 491636.235],
     [121339.479, 491635.983],
     [121339.314, 491635.715],
     [121339.177, 491635.442],
     [121339.063, 491635.157],
     [121338.974, 491634.865],
     [121338.91, 491634.565],
     [121338.872, 491634.262],
     [121338.86, 491633.956],
     [121338.874, 491633.65],
     [121338.914, 491633.347],
     [121338.979, 491633.048],
     [121339.07, 491632.756],
     [121339.185, 491632.472],
     [121339.323, 491632.2],
     [121339.485, 491631.94],
     [121339.668, 491631.695],
     [121339.871, 491631.466],
     [121340.093, 491631.255],
     [121340.332, 491631.064],
     [121339.992, 491630.698],
     [121342.306, 491628.89],
     [121347.98, 491624.439],
     [121346.066, 491621.962],
     [121347.903, 491620.525],
     [121337.409, 491607.093],
     [121337.345, 491607.011],
     [121339.732, 491605.125],
     [121339.22, 491604.471],
     [121341.687, 491602.541],
     [121329.884, 491587.454],
     [121329.964, 491587.405],
     [121333.962, 491584.252],
     [121335.121, 491585.719],
     [121339.042, 491582.627],
     [121353.539, 491601.144],
     [121348.668, 491604.965],
     [121359.789, 491619.185],
     [121360.875, 491620.573],
     [121372.063, 491634.878]]]]}}

### Markets

#### Endpoint

In [ ]:
404

### Basic Register of Addresses and Buildings - (BAG) Basisregistratie adressen en gebouwen (BAG)

#### Endpoint

https://data.amsterdam.nl/catalogus/67

https://api.data.amsterdam.nl/v1/docs/datasets/bag.html
https://api.data.amsterdam.nl/v1/bag/woonplaatsen
https://api.data.amsterdam.nl/v1/bag/woonplaatsen?_expandScope=heeftHoofdadres => wrong

In [68]:
url_bag="https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten?_expandScope=heeftHoofdadres"
response_bag = requests.get(url_bag)
print(response_bag.status_code)

200

#### Response

In [69]:
info_bag = response_bag.json()
info_bag

{'_embedded': {'verblijfsobjecten': [{'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/bag/verblijfsobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363010000543292?volgnummer=1',
      'title': '0363010000543292',
      'identificatie': '0363010000543292',
      'volgnummer': 1},
     'heeftHoofdadres': {'href': 'https://api.data.amsterdam.nl/v1/bag/nummeraanduidingen/0363200000006110?volgnummer=1',
      'title': '0363200000006110',
      'identificatie': '0363200000006110',
      'volgnummer': 1},
     'ligtInBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000029?volgnummer=1',
      'title': 'Anjeliersbuurt-Zuid',
      'identificatie': '03630980000029',
      'volgnummer': 1},
     'heeftDossier': None,
     'heeftNevenadres': [],
     'ligtInPanden': [{'href': 'https://api.data.amsterdam.nl/v1/bag/panden/0363100012174784?volgnummer=4',
       'title': '0363100012174784',
       'identificatie': '0363100012174784',
       'volgnummer': 4,
       'beginGeldigheid': '2023-09-28T00:00:00'}],
     'heeftOnderzoeken': []},
    'identificatie': '0363010000543292',
    'volgnummer': 1,
    'plusvolgnummer': 8,
    'registratiedatum': '2010-11-04T21:57:01',
    'cbsNummer': None,
    'indicatieWoningvoorraad': None,
    'financieringscodeCode': None,
    'financieringscodeOmschrijving': None,
    'geconstateerd': False,
    'heeftHoofdadresId': '0363200000006110',
    'geometrie': {'type': 'Point', 'coordinates': [120700.0, 487936.0]},
    'oppervlakte': 30,
    'statusCode': None,
    'statusOmschrijving': 'Verblijfsobject in gebruik',
    'beginGeldigheid': '2010-09-09T00:00:00',
    'eindGeldigheid': None,
    'documentdatum': '2010-09-09',
    'documentnummer': 'GV00000406',
    'gebruiksdoelWoonfunctieCode': None,
    'gebruiksdoelWoonfunctieOmschrijving': None,
    'gebruiksdoelGezondheidszorgfunctieCode': None,
    'gebruiksdoelGezondheidszorgfunctieOmschrijving': None,
    'aantalEenhedenComplex': None,
    'verdiepingToegang': 0,
    'aantalBouwlagen': None,
    'hoogsteBouwlaag': None,
    'laagsteBouwlaag': None,
    'aantalKamers': None,
    'eigendomsverhoudingCode': None,
    'eigendomsverhoudingOmschrijving': None,
    'feitelijkGebruikCode': None,
    'feitelijkGebruikOmschrijving': None,
    'redenopvoerCode': None,
    'redenopvoerOmschrijving': None,
    'redenafvoerCode': None,
    'redenafvoerOmschrijving': None,
    'ligtInBuurtId': '03630980000029',
    'heeftDossierId': None,
    'bagprocesCode': None,
    'bagprocesOmschrijving': None,
    'datumActueelTot': None,
    'gebruiksdoel': [{'code': None, 'omschrijving': 'winkelfunctie'}],
    'toegang': []},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/bag/verblijfsobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363010000543293?volgnummer=2',
      'title': '0363010000543293',
      'identificatie': '0363010000543293',
      'volgnummer': 2},
     'heeftHoofdadres': {'href': 'https://api.data.amsterdam.nl/v1/bag/nummeraanduidingen/0363200000006111?volgnummer=1',
      'title': '0363200000006111',
      'identificatie': '0363200000006111',
      'volgnummer': 1},
     'ligtInBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000029?volgnummer=1',
      'title': 'Anjeliersbuurt-Zuid',
      'identificatie': '03630980000029',
      'volgnummer': 1},
     'heeftDossier': None,
     'heeftNevenadres': [],
     'ligtInPanden': [{'href': 'https://api.data.amsterdam.nl/v1/bag/panden/0363100012174784?volgnummer=4',
       'title': '0363100012174784',
       'identificatie': '0363100012174784',
       'volgnummer': 4,
       'beginGeldigheid': '2023-09-28T00:00:00'}],
     'heeftOnderzoeken': []},
    'identificatie': '0363010000543293',
    'volgnummer': 2,
    'plusvolgnummer': 10,
    'registratiedatum': '2012-08-09T21:07:08',
    'cbsNummer': None,
    'indicatieWoningvoorraad': None,
    'financieringscodeCode': None,
    'financieringscodeOmschrijving': None,
    'geconstateerd': False,
    'heeftHoofdadresId': '0363200000006111',
    'geometrie': {'type': 'Point', 'coordinates': [120700.0, 487936.0]},
    'oppervlakte': 32,
    'statusCode': None,
    'statusOmschrijving': 'Verblijfsobject in gebruik',
    'beginGeldigheid': '2012-08-09T00:00:00',
    'eindGeldigheid': None,
    'documentdatum': '2012-08-09',
    'documentnummer': 'GV00001551',
    'gebruiksdoelWoonfunctieCode': None,
    'gebruiksdoelWoonfunctieOmschrijving': None,
    'gebruiksdoelGezondheidszorgfunctieCode': None,
    'gebruiksdoelGezondheidszorgfunctieOmschrijving': None,
    'aantalEenhedenComplex': None,
    'verdiepingToegang': 1,
    'aantalBouwlagen': 1,
    'hoogsteBouwlaag': None,
    'laagsteBouwlaag': None,
    'aantalKamers': 2,
    'eigendomsverhoudingCode': None,
    'eigendomsverhoudingOmschrijving': None,
    'feitelijkGebruikCode': None,
    'feitelijkGebruikOmschrijving': None,
    'redenopvoerCode': None,
    'redenopvoerOmschrijving': None,
    'redenafvoerCode': None,
    'redenafvoerOmschrijving': None,
    'ligtInBuurtId': '03630980000029',
    'heeftDossierId': None,
    'bagprocesCode': None,
    'bagprocesOmschrijving': 'Muteren naar aanleiding van signalering',
    'datumActueelTot': None,
    'gebruiksdoel': [{'code': None, 'omschrijving': 'woonfunctie'}],
    'toegang': [{'code': None, 'omschrijving': 'Trap'}]},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/bag/verblijfsobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363010000543294?volgnummer=1',
      'title': '0363010000543294',
      'identificatie': '0363010000543294',
      'volgnummer': 1},
     'heeftHoofdadres': {'href': 'https://api.data.amsterdam.nl/v1/bag/nummeraanduidingen/0363200000006112?volgnummer=1',
      'title': '0363200000006112',
      'identificatie': '0363200000006112',
      'volgnummer': 1},
     'ligtInBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000029?volgnummer=1',
      'title': 'Anjeliersbuurt-Zuid',
      'identificatie': '03630980000029',
      'volgnummer': 1},
     'heeftDossier': None,
     'heeftNevenadres': [],
     'ligtInPanden': [{'href': 'https://api.data.amsterdam.nl/v1/bag/panden/0363100012174784?volgnummer=4',
       'title': '0363100012174784',
       'identificatie': '0363100012174784',
       'volgnummer': 4,
       'beginGeldigheid': '2023-09-28T00:00:00'}],
     'heeftOnderzoeken': []},
    'identificatie': '0363010000543294',
    'volgnummer': 1,
    'plusvolgnummer': 7,
    'registratiedatum': '2010-11-04T21:57:02',
    'cbsNummer': None,
    'indicatieWoningvoorraad': None,
    'financieringscodeCode': None,
    'financieringscodeOmschrijving': None,
    'geconstateerd': False,
    'heeftHoofdadresId': '0363200000006112',
    'geometrie': {'type': 'Point', 'coordinates': [120700.0, 487936.0]},
    'oppervlakte': 48,
    'statusCode': None,
    'statusOmschrijving': 'Verblijfsobject in gebruik',
    'beginGeldigheid': '2010-09-09T00:00:00',
    'eindGeldigheid': None,
    'documentdatum': '2010-09-09',
    'documentnummer': 'GV00000406',
    'gebruiksdoelWoonfunctieCode': None,
    'gebruiksdoelWoonfunctieOmschrijving': None,
    'gebruiksdoelGezondheidszorgfunctieCode': None,
    'gebruiksdoelGezondheidszorgfunctieOmschrijving': None,
    'aantalEenhedenComplex': None,
    'verdiepingToegang': 2,
    'aantalBouwlagen': 2,
    'hoogsteBouwlaag': None,
    'laagsteBouwlaag': None,
    'aantalKamers': 2,
    'eigendomsverhoudingCode': None,
    'eigendomsverhoudingOmschrijving': None,
    'feitelijkGebruikCode': None,
    'feitelijkGebruikOmschrijving': None,
    'redenopvoerCode': None,
    'redenopvoerOmschrijving': None,
    'redenafvoerCode': None,
    'redenafvoerOmschrijving': None,
    'ligtInBuurtId': '03630980000029',
    'heeftDossierId': None,
    'bagprocesCode': None,
    'bagprocesOmschrijving': None,
    'datumActueelTot': None,
    'gebruiksdoel': [{'code': None, 'omschrijving': 'woonfunctie'}],
    'toegang': [{'code': None, 'omschrijving': 'Trap'}]},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/bag/verblijfsobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363010000543296?volgnummer=1',
      'title': '0363010000543296',
      'identificatie': '0363010000543296',
      'volgnummer': 1},
     'heeftHoofdadres': {'href': 'https://api.data.amsterdam.nl/v1/bag/nummeraanduidingen/0363200000006114?volgnummer=1',
      'title': '0363200000006114',
      'identificatie': '0363200000006114',
      'volgnummer': 1},
     'ligtInBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000029?volgnummer=1',
      'title': 'Anjeliersbuurt-Zuid',
      'identificatie': '03630980000029',
      'volgnummer': 1},
     'heeftDossier': None,
     'heeftNevenadres': [],
     'ligtInPanden': [{'href': 'https://api.data.amsterdam.nl/v1/bag/panden/0363100012174784?volgnummer=4',
       'title': '0363100012174784',
       'identificatie': '0363100012174784',
       'volgnummer': 4,
       'beginGeldigheid': '2023-09-28T00:00:00'}],
     'heeftOnderzoeken': []},
    'identificatie': '0363010000543296',
    'volgnummer': 1,
    'plusvolgnummer': 7,
    'registratiedatum': '2010-11-04T21:57:02',
    'cbsNummer': None,
    'indicatieWoningvoorraad': None,
    'financieringscodeCode': None,
    'financieringscodeOmschrijving': None,
    'geconstateerd': False,
    'heeftHoofdadresId': '0363200000006114',
    'geometrie': {'type': 'Point', 'coordinates': [120703.0, 487931.0]},
    'oppervlakte': 32,
    'statusCode': None,
    'statusOmschrijving': 'Verblijfsobject in gebruik',
    'beginGeldigheid': '2010-09-09T00:00:00',
    'eindGeldigheid': None,
    'documentdatum': '2010-09-09',
    'documentnummer': 'GV00000406',
    'gebruiksdoelWoonfunctieCode': None,
    'gebruiksdoelWoonfunctieOmschrijving': None,
    'gebruiksdoelGezondheidszorgfunctieCode': None,
    'gebruiksdoelGezondheidszorgfunctieOmschrijving': None,
    'aantalEenhedenComplex': None,
    'verdiepingToegang': 1,
    'aantalBouwlagen': 1,
    'hoogsteBouwlaag': None,
    'laagsteBouwlaag': None,
    'aantalKamers': 2,
    'eigendomsverhoudingCode': None,
    'eigendomsverhoudingOmschrijving': None,
    'feitelijkGebruikCode': None,
    'feitelijkGebruikOmschrijving': None,
    'redenopvoerCode': None,
    'redenopvoerOmschrijving': None,
    'redenafvoerCode': None,
    'redenafvoerOmschrijving': None,
    'ligtInBuurtId': '03630980000029',
    'heeftDossierId': None,
    'bagprocesCode': None,
    'bagprocesOmschrijving': None,
    'datumActueelTot': None,
    'gebruiksdoel': [{'code': None, 'omschrijving': 'woonfunctie'}],
    'toegang': [{'code': None, 'omschrijving': 'Trap'}]},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/bag/verblijfsobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363010000543297?volgnummer=2',
      'title': '0363010000543297',
      'identificatie': '0363010000543297',
      'volgnummer': 2},
     'heeftHoofdadres': {'href': 'https://api.data.amsterdam.nl/v1/bag/nummeraanduidingen/0363200000006115?volgnummer=1',
      'title': '0363200000006115',
      'identificatie': '0363200000006115',
      'volgnummer': 1},
     'ligtInBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000029?volgnummer=1',
      'title': 'Anjeliersbuurt-Zuid',
      'identificatie': '03630980000029',
      'volgnummer': 1},
     'heeftDossier': None,
     'heeftNevenadres': [],
     'ligtInPanden': [{'href': 'https://api.data.amsterdam.nl/v1/bag/panden/0363100012174784?volgnummer=4',
       'title': '0363100012174784',
       'identificatie': '0363100012174784',
       'volgnummer': 4,
       'beginGeldigheid': '2023-09-28T00:00:00'}],
     'heeftOnderzoeken': []},
    'identificatie': '0363010000543297',
    'volgnummer': 2,
    'plusvolgnummer': 10,
    'registratiedatum': '2013-02-04T19:03:37',
    'cbsNummer': None,
    'indicatieWoningvoorraad': None,
    'financieringscodeCode': None,
    'financieringscodeOmschrijving': None,
    'geconstateerd': False,
    'heeftHoofdadresId': '0363200000006115',
    'geometrie': {'type': 'Point', 'coordinates': [120703.0, 487931.0]},
    'oppervlakte': 32,
    'statusCode': None,
    'statusOmschrijving': 'Verblijfsobject in gebruik',
    'beginGeldigheid': '2013-02-04T00:00:00',
    'eindGeldigheid': None,
    'documentdatum': '2013-02-04',
    'documentnummer': 'GV00001616_AC00AC',
    'gebruiksdoelWoonfunctieCode': None,
    'gebruiksdoelWoonfunctieOmschrijving': None,
    'gebruiksdoelGezondheidszorgfunctieCode': None,
    'gebruiksdoelGezondheidszorgfunctieOmschrijving': None,
    'aantalEenhedenComplex': None,
    'verdiepingToegang': 2,
    'aantalBouwlagen': 1,
    'hoogsteBouwlaag': None,
    'laagsteBouwlaag': None,
    'aantalKamers': 2,
    'eigendomsverhoudingCode': None,
    'eigendomsverhoudingOmschrijving': None,
    'feitelijkGebruikCode': None,
    'feitelijkGebruikOmschrijving': None,
    'redenopvoerCode': None,
    'redenopvoerOmschrijving': None,
    'redenafvoerCode': None,
    'redenafvoerOmschrijving': None,
    'ligtInBuurtId': '03630980000029',
    'heeftDossierId': None,
    'bagprocesCode': None,
    'bagprocesOmschrijving': 'Muteren naar aanleiding van signalering',
    'datumActueelTot': None,
    'gebruiksdoel': [{'code': None, 'omschrijving': 'woonfunctie'}],
    'toegang': [{'code': None, 'omschrijving': 'Trap'}]},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/bag/verblijfsobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363010000543300?volgnummer=2',
      'title': '0363010000543300',
      'identificatie': '0363010000543300',
      'volgnummer': 2},
     'heeftHoofdadres': {'href': 'https://api.data.amsterdam.nl/v1/bag/nummeraanduidingen/0363200000006119?volgnummer=1',
      'title': '0363200000006119',
      'identificatie': '0363200000006119',
      'volgnummer': 1},
     'ligtInBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000029?volgnummer=1',
      'title': 'Anjeliersbuurt-Zuid',
      'identificatie': '03630980000029',
      'volgnummer': 1},
     'heeftDossier': None,
     'heeftNevenadres': [],
     'ligtInPanden': [{'href': 'https://api.data.amsterdam.nl/v1/bag/panden/0363100012174784?volgnummer=4',
       'title': '0363100012174784',
       'identificatie': '0363100012174784',
       'volgnummer': 4,
       'beginGeldigheid': '2023-09-28T00:00:00'}],
     'heeftOnderzoeken': []},
    'identificatie': '0363010000543300',
    'volgnummer': 2,
    'plusvolgnummer': 10,
    'registratiedatum': '2013-02-04T19:03:39',
    'cbsNummer': None,
    'indicatieWoningvoorraad': None,
    'financieringscodeCode': None,
    'financieringscodeOmschrijving': None,
    'geconstateerd': False,
    'heeftHoofdadresId': '0363200000006119',
    'geometrie': {'type': 'Point', 'coordinates': [120703.0, 487926.0]},
    'oppervlakte': 32,
    'statusCode': None,
    'statusOmschrijving': 'Verblijfsobject in gebruik',
    'beginGeldigheid': '2013-02-04T00:00:00',
    'eindGeldigheid': None,
    'documentdatum': '2013-02-04',
    'documentnummer': 'GV00001616_AC00AC',
    'gebruiksdoelWoonfunctieCode': None,
    'gebruiksdoelWoonfunctieOmschrijving': None,
    'gebruiksdoelGezondheidszorgfunctieCode': None,
    'gebruiksdoelGezondheidszorgfunctieOmschrijving': None,
    'aantalEenhedenComplex': None,
    'verdiepingToegang': 1,
    'aantalBouwlagen': 1,
    'hoogsteBouwlaag': None,
    'laagsteBouwlaag': None,
    'aantalKamers': 2,
    'eigendomsverhoudingCode': None,
    'eigendomsverhoudingOmschrijving': None,
    'feitelijkGebruikCode': None,
    'feitelijkGebruikOmschrijving': None,
    'redenopvoerCode': None,
    'redenopvoerOmschrijving': None,
    'redenafvoerCode': None,
    'redenafvoerOmschrijving': None,
    'ligtInBuurtId': '03630980000029',
    'heeftDossierId': None,
    'bagprocesCode': None,
    'bagprocesOmschrijving': 'Muteren naar aanleiding van signalering',
    'datumActueelTot': None,
    'gebruiksdoel': [{'code': None, 'omschrijving': 'woonfunctie'}],
    'toegang': [{'code': None, 'omschrijving': 'Trap'}]},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/bag/verblijfsobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363010000543301?volgnummer=1',
      'title': '0363010000543301',
      'identificatie': '0363010000543301',
      'volgnummer': 1},
     'heeftHoofdadres': {'href': 'https://api.data.amsterdam.nl/v1/bag/nummeraanduidingen/0363200000006120?volgnummer=1',
      'title': '0363200000006120',
      'identificatie': '0363200000006120',
      'volgnummer': 1},
     'ligtInBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000029?volgnummer=1',
      'title': 'Anjeliersbuurt-Zuid',
      'identificatie': '03630980000029',
      'volgnummer': 1},
     'heeftDossier': None,
     'heeftNevenadres': [],
     'ligtInPanden': [{'href': 'https://api.data.amsterdam.nl/v1/bag/panden/0363100012174784?volgnummer=4',
       'title': '0363100012174784',
       'identificatie': '0363100012174784',
       'volgnummer': 4,
       'beginGeldigheid': '2023-09-28T00:00:00'}],
     'heeftOnderzoeken': []},
    'identificatie': '0363010000543301',
    'volgnummer': 1,
    'plusvolgnummer': 7,
    'registratiedatum': '2010-11-04T21:57:02',
    'cbsNummer': None,
    'indicatieWoningvoorraad': None,
    'financieringscodeCode': None,
    'financieringscodeOmschrijving': None,
    'geconstateerd': False,
    'heeftHoofdadresId': '0363200000006120',
    'geometrie': {'type': 'Point', 'coordinates': [120703.0, 487926.0]},
    'oppervlakte': 32,
    'statusCode': None,
    'statusOmschrijving': 'Verblijfsobject in gebruik',
    'beginGeldigheid': '2010-09-09T00:00:00',
    'eindGeldigheid': None,
    'documentdatum': '2010-09-09',
    'documentnummer': 'GV00000406',
    'gebruiksdoelWoonfunctieCode': None,
    'gebruiksdoelWoonfunctieOmschrijving': None,
    'gebruiksdoelGezondheidszorgfunctieCode': None,
    'gebruiksdoelGezondheidszorgfunctieOmschrijving': None,
    'aantalEenhedenComplex': None,
    'verdiepingToegang': 2,
    'aantalBouwlagen': 1,
    'hoogsteBouwlaag': None,
    'laagsteBouwlaag': None,
    'aantalKamers': 2,
    'eigendomsverhoudingCode': None,
    'eigendomsverhoudingOmschrijving': None,
    'feitelijkGebruikCode': None,
    'feitelijkGebruikOmschrijving': None,
    'redenopvoerCode': None,
    'redenopvoerOmschrijving': None,
    'redenafvoerCode': None,
    'redenafvoerOmschrijving': None,
    'ligtInBuurtId': '03630980000029',
    'heeftDossierId': None,
    'bagprocesCode': None,
    'bagprocesOmschrijving': None,
    'datumActueelTot': None,
    'gebruiksdoel': [{'code': None, 'omschrijving': 'woonfunctie'}],
    'toegang': [{'code': None, 'omschrijving': 'Trap'}]},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/bag/verblijfsobjecten/v1',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363010000543304?volgnummer=2',
      'title': '0363010000543304',
      'identificatie': '0363010000543304',
      'volgnummer': 2},
     'heeftHoofdadres': {'href': 'https://api.data.amsterdam.nl/v1/bag/nummeraanduidingen/0363200000006123?volgnummer=1',
      'title': '0363200000006123',
      'identificatie': '0363200000006123',
      'volgnummer': 1},
     'ligtInBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000029?volgnummer=1',
      'title': 'Anjeliersbuurt-Zuid',
      'identificatie': '03630980000029',
      'volgnummer': 1},
     'heeftDossier': None,
     'heeftNevenadres': [],
     'ligtInPanden': [{'href': 'https://api.data.amsterdam.nl/v1/bag/panden/0363100012174784?volgnummer=4',

In [70]:
info_bag['_embedded'].keys()

dict_keys(['verblijfsobjecten', 'heeftHoofdadres'])

In [71]:
info_bag['_embedded']['verblijfsobjecten'][0].keys()

dict_keys(['_links', 'identificatie', 'volgnummer', 'plusvolgnummer', 'registratiedatum', 'cbsNummer', 'indicatieWoningvoorraad', 'financieringscodeCode', 'financieringscodeOmschrijving', 'geconstateerd', 'heeftHoofdadresId', 'geometrie', 'oppervlakte', 'statusCode', 'statusOmschrijving', 'beginGeldigheid', 'eindGeldigheid', 'documentdatum', 'documentnummer', 'gebruiksdoelWoonfunctieCode', 'gebruiksdoelWoonfunctieOmschrijving', 'gebruiksdoelGezondheidszorgfunctieCode', 'gebruiksdoelGezondheidszorgfunctieOmschrijving', 'aantalEenhedenComplex', 'verdiepingToegang', 'aantalBouwlagen', 'hoogsteBouwlaag', 'laagsteBouwlaag', 'aantalKamers', 'eigendomsverhoudingCode', 'eigendomsverhoudingOmschrijving', 'feitelijkGebruikCode', 'feitelijkGebruikOmschrijving', 'redenopvoerCode', 'redenopvoerOmschrijving', 'redenafvoerCode', 'redenafvoerOmschrijving', 'ligtInBuurtId', 'heeftDossierId', 'bagprocesCode', 'bagprocesOmschrijving', 'datumActueelTot', 'gebruiksdoel', 'toegang'])

In [72]:
info_bag['_embedded']['heeftHoofdadres'][0].keys()

dict_keys(['_links', 'identificatie', 'volgnummer', 'plusvolgnummer', 'registratiedatum', 'huisnummer', 'geconstateerd', 'huisletter', 'huisnummertoevoeging', 'postcode', 'ligtInWoonplaatsId', 'beginGeldigheid', 'eindGeldigheid', 'ligtAanOpenbareruimteId', 'typeAdresseerbaarObjectCode', 'typeAdresseerbaarObjectOmschrijving', 'documentdatum', 'documentnummer', 'statusCode', 'statusOmschrijving', 'typeAdres', 'adresseertVerblijfsobjectId', 'adresseertLigplaatsId', 'adresseertStandplaatsId', 'heeftDossierId', 'bagprocesCode', 'bagprocesOmschrijving', 'datumActueelTot'])

#### Iteration through pages

In [82]:

# This variable starts with the same value as we had for url_bag,
# but will change as the code goes throuh the pages:
headers = {
    "X-Api-Key": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0OTk2Mzk2MTk0MTcyNjEwNjM1IiwiZXhwIjoxODE0MzU1ODQ1fQ.LfXJNucSt2nDBrgA60ElAZdpz89--auFrCQbU3Re17e-MYHeZhBPc34x0nVxc-Ri4xCB0LuiST2UDmZnaOnnAg"
}
url_pagination="https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten?_expandScope=heeftHoofdadres"

all_records_heeftHoofdadres = []
page = 1

while url_pagination:

    print(f"Downloading page {page}")

    response_page = requests.get(url_pagination)
    response_page.raise_for_status()

    info_page = response_page.json()

    # Add the records from this page
    all_records_heeftHoofdadres.extend(info_page["_embedded"]["heeftHoofdadres"])

    # Get the URL for the next page (if any)
    url_pagination = info_page["_links"].get("next", {}).get("href")

    page += 1

Downloading page 1
Downloading page 2
Downloading page 3
Downloading page 4
Downloading page 5
Downloading page 6
Downloading page 7
Downloading page 8
Downloading page 9
Downloading page 10
Downloading page 11
Downloading page 12
Downloading page 13
Downloading page 14
Downloading page 15
Downloading page 16
Downloading page 17
Downloading page 18
Downloading page 19
Downloading page 20
Downloading page 21
Downloading page 22
Downloading page 23
Downloading page 24
Downloading page 25
Downloading page 26
Downloading page 27
Downloading page 28
Downloading page 29
Downloading page 30
Downloading page 31
Downloading page 32
Downloading page 33
Downloading page 34
Downloading page 35
Downloading page 36
Downloading page 37
Downloading page 38
Downloading page 39
Downloading page 40
Downloading page 41
Downloading page 42
Downloading page 43
Downloading page 44
Downloading page 45
Downloading page 46
Downloading page 47
Downloading page 48
Downloading page 49
Downloading page 50
Downloading page 51
Downloading page 52
Downloading page 53
Downloading page 54
Downloading page 55
Downloading page 56
Downloading page 57
Downloading page 58
Downloading page 59
Downloading page 60
Downloading page 61
Downloading page 62
Downloading page 63
Downloading page 64
Downloading page 65
Downloading page 66
Downloading page 67
Downloading page 68
Downloading page 69
Downloading page 70
Downloading page 71
Downloading page 72
Downloading page 73
Downloading page 74
Downloading page 75
Downloading page 76
Downloading page 77
Downloading page 78
Downloading page 79
Downloading page 80
Downloading page 81
Downloading page 82
Downloading page 83
Downloading page 84
Downloading page 85
Downloading page 86
Downloading page 87
Downloading page 88
Downloading page 89
Downloading page 90
Downloading page 91
Downloading page 92
Downloading page 93
Downloading page 94
Downloading page 95
Downloading page 96
Downloading page 97
Downloading page 98
Downloading page 99
Downloading page 100
Downloading page 101

HTTPError: 403 Client Error: Forbidden for url: https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten?_expandScope=heeftHoofdadres&page=101

In [102]:
info_page["_links"]

{'self': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten?_expandScope=heeftHoofdadres&page=100'},
 'next': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten?_expandScope=heeftHoofdadres&page=101'},
 'previous': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten?_expandScope=heeftHoofdadres&page=99'}}

In [ ]:

url_pagination

In [116]:
headers = {
    "X-Api-Key": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0OTk2Mzk2MTk0MTcyNjEwNjM1IiwiZXhwIjoxODE0MzU1ODQ1fQ.LfXJNucSt2nDBrgA60ElAZdpz89--auFrCQbU3Re17e-MYHeZhBPc34x0nVxc-Ri4xCB0LuiST2UDmZnaOnnAg"
}

url_test_pagination="https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten?_expandScope=heeftHoofdadres&page=101"
url_test2_pagination="https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten?_expandScope=heeftHoofdadres&_pageSize=100&_count=true"
url_test3_pagination="https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten?page=101"


response_test_page = requests.get(url_test3_pagination, headers=headers)
print(response_test_page.status_code)

403

In [110]:
response_test_page_object= response_test_page.json()

In [111]:
response_test_page_object['page']['totalPages']

5820

In [112]:
response_test_page_object["page"]["totalElements"]

581965

#### Transform to Data Frame

In [83]:
len(all_records_heeftHoofdadres)

2000

In [84]:
municipal_bag_data = pd.DataFrame(all_records_heeftHoofdadres)

In [85]:
municipal_bag_data

,_links,identificatie,volgnummer,plusvolgnummer,registratiedatum,huisnummer,geconstateerd,huisletter,huisnummertoevoeging,postcode,...,statusCode,statusOmschrijving,typeAdres,adresseertVerblijfsobjectId,adresseertLigplaatsId,adresseertStandplaatsId,heeftDossierId,bagprocesCode,bagprocesOmschrijving,datumActueelTot
0,{'schema': 'https://schemas.data.amsterdam.nl/...,0363200000006110,1,3,2010-11-04T21:57:01,1,False,NaN,H,1015NR,...,None,Naamgeving uitgegeven,Hoofdadres,0363010000543292,None,None,None,None,None,None
1,{'schema': 'https://schemas.data.amsterdam.nl/...,0363200000006111,1,3,2010-11-04T21:57:01,1,False,NaN,1,1015NR,...,None,Naamgeving uitgegeven,Hoofdadres,0363010000543293,None,None,None,None,None,None
2,{'schema': 'https://schemas.data.amsterdam.nl/...,0363200000006112,1,3,2010-11-04T21:57:01,1,False,NaN,2,1015NR,...,None,Naamgeving uitgegeven,Hoofdadres,0363010000543294,None,None,None,None,None,None
3,{'schema': 'https://schemas.data.amsterdam.nl/...,0363200000006114,1,3,2010-11-04T21:57:02,3,False,NaN,1,1015NR,...,None,Naamgeving uitgegeven,Hoofdadres,0363010000543296,None,None,None,None,None,None
4,{'schema': 'https://schemas.data.amsterdam.nl/...,0363200000006115,1,3,2010-11-04T21:57:02,3,False,NaN,2,1015NR,...,None,Naamgeving uitgegeven,Hoofdadres,0363010000543297,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,{'schema': 'https://schemas.data.amsterdam.nl/...,0363200000008848,1,3,2010-11-04T22:03:08,46,False,A,NaN,1072NM,...,None,Naamgeving uitgegeven,Hoofdadres,0363010000546003,None,None,None,None,None,None
1996,{'schema': 'https://schemas.data.amsterdam.nl/...,0363200000008849,1,3,2010-11-04T22:03:08,46,False,B,NaN,1072NM,...,None,Naamgeving uitgegeven,Hoofdadres,0363010000546004,None,None,None,None,None,None
1997,{'schema': 'https://schemas.data.amsterdam.nl/...,0363200000008850,1,3,2010-11-04T22:03:08,46,False,C,NaN,1072NM,...,None,Naamgeving uitgegeven,Hoofdadres,0363010000546005,None,None,None,None,None,None
1998,{'schema': 'https://schemas.data.amsterdam.nl/...,0363200000008851,1,3,2010-11-04T22:03:08,46,False,D,NaN,1072NM,...,None,Naamgeving uitgegeven,Hoofdadres,0363010000546006,None,None,None,None,None,None
1999,{'schema': 'https://schemas.data.amsterdam.nl/...,0363200000008852,1,3,2010-11-04T22:03:09,46,False,E,NaN,1072NM,...,None,Naamgeving uitgegeven,Hoofdadres,0363010000546007,None,None,None,None,None,None

In [87]:
municipal_bag_data['postcode'].unique()

<StringArray>
['1015NR', '1094JX', '1094KL', '1069LK', '1094JZ', '1022XE', '1094KA',
 '1094KB', '1094KC', '1094KD',
 ...
 '1072BD', '1072BH', '1016VR', '1072NK', '1072NA', '1091ED', '1072NL',
 '1072NB', '1053EK', '1072NM']
Length: 126, dtype: str

In [89]:
found_postCode = municipal_bag_data['postcode'].unique()

In [92]:
type(found_postCode[1])

str

In [95]:
found_postCode = [
    postcode[:4] if isinstance(postcode, str) else postcode
    for postcode in found_postCode
]
found_postCode

['1015',
 '1094',
 '1094',
 '1069',
 '1094',
 '1022',
 '1094',
 '1094',
 '1094',
 '1094',
 '1094',
 '1052',
 '1094',
 '1094',
 '1094',
 '1094',
 '1094',
 '1094',
 '1094',
 '1094',
 '1016',
 '1016',
 '1011',
 '1013',
 '1073',
 '1091',
 '1091',
 '1091',
 '1073',
 '1052',
 '1015',
 '1052',
 '1013',
 '1013',
 '1092',
 '1018',
 '1095',
 '1095',
 '1018',
 '1018',
 '1054',
 '1054',
 '1017',
 '1011',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1031',
 '1015',
 '1073',
 '1015',
 '1013',
 '1066',
 '1015',
 '1054',
 '1054',
 '1054',
 '1015',
 '1052',
 '1074',
 '1019',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1012',
 '1054',
 '1012',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1054',
 '1102',
 '1051',
 '1054',
 '1054',
 '1054',
 '1054',
 '1052',
 '1052',
 '1052',
 '1052',
 '1052',
 '1052',
 '1016',
 '1052',
 '1052',
 '1072',
 '1072',
 '1072',
 nan,
 '1072',
 '1072',
 '1072',
 '1016',
 '1072',
 '1072',
 '1091',
 '1072',
 '1072',
 '1053',
 '1072']

In [100]:
unique_postcodes = set(found_postCode)
len(unique_postcodes)

25

In [101]:
unique_postcodes

{'1011',
 '1012',
 '1013',
 '1015',
 '1016',
 '1017',
 '1018',
 '1019',
 '1022',
 '1031',
 '1051',
 '1052',
 '1053',
 '1054',
 '1066',
 '1069',
 '1072',
 '1073',
 '1074',
 '1091',
 '1092',
 '1094',
 '1095',
 '1102',
 nan}

### Trash

Distance from homes to trash deposits - Loopafstanden

https://data.amsterdam.nl/catalogus/56

In [ ]:
Service areas - trash

In [ ]:
https://data.amsterdam.nl/catalogus/55

#### Tests

In [122]:
url_test1_trash="https://api.data.amsterdam.nl/v1/huishoudelijkafval/container"
url_test2_trash="https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?&_pageSize=100&_count=true"
url_test3_trash="https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?fractieCode=2&_pageSize=100&_count=true"


response_test3_trash = requests.get(url_test3_trash)
print(response_test3_trash.status_code)
response_test3_trash_object= response_test3_trash.json()
response_test3_trash_object

200

{'_embedded': {'container': [{'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/10004',
      'title': '10004',
      'id': '10004'},
     'cluster': None,
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/10003',
      'title': '10003',
      'id': '10003'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/348',
      'title': '348',
      'id': '348'},
     'bagHoofdadresVerblijfsobject': None,
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000386',
      'title': '03630980000386',
      'identificatie': '03630980000386'},
     'bagOpenbareruimte': None,
     'bagNummeraanduiding': None},
    'id': '10004',
    'idNummer': 'GL 7226',
    'serienummer': 'BAO01404',
    'clusterId': None,
    'eigenaarId': '184',
    'eigenaarNaam': 'Amsterdam Dump Locatie',
    'status': 0,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2012-03-29',
    'datumPlaatsing': '2012-03-29',
    'datumOperationeel': None,
    'datumAflopenGarantie': '2012-01-01',
    'datumOplevering': '2012-03-29',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': False,
    'locatieId': '10003',
    'geometrie': {'type': 'Point',
     'coordinates': [125270.13808738378, 484296.416385144]},
    'typeId': '348',
    'bagHoofdadresVerblijfsobjectId': None,
    'gbdBuurtId': '03630980000386',
    'bagOpenbareruimteId': None,
    'bagNummeraanduidingId': None,
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': None,
    'containerUnitCardLezerId': None,
    'containerKleur': 'Hamerslag dennengroen',
    'containerMark': None,
    'containerDatumVervanging': None,
    'containerDatumWijziging': '2018-07-01T02:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': None},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/10006',
      'title': '10006',
      'id': '10006'},
     'cluster': None,
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/32498',
      'title': '32498',
      'id': '32498'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/348',
      'title': '348',
      'id': '348'},
     'bagHoofdadresVerblijfsobject': None,
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000386',
      'title': '03630980000386',
      'identificatie': '03630980000386'},
     'bagOpenbareruimte': None,
     'bagNummeraanduiding': None},
    'id': '10006',
    'idNummer': 'GL 7227',
    'serienummer': 'BAO01405',
    'clusterId': None,
    'eigenaarId': '184',
    'eigenaarNaam': 'Amsterdam Dump Locatie',
    'status': 0,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2012-03-29',
    'datumPlaatsing': '2016-01-25',
    'datumOperationeel': '2016-01-25',
    'datumAflopenGarantie': '2016-01-25',
    'datumOplevering': '2012-03-29',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': False,
    'locatieId': '32498',
    'geometrie': {'type': 'Point',
     'coordinates': [125172.99804757624, 484171.99365785054]},
    'typeId': '348',
    'bagHoofdadresVerblijfsobjectId': None,
    'gbdBuurtId': '03630980000386',
    'bagOpenbareruimteId': None,
    'bagNummeraanduidingId': None,
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': None,
    'containerUnitCardLezerId': None,
    'containerKleur': 'Hamerslag dennengroen',
    'containerMark': None,
    'containerDatumVervanging': None,
    'containerDatumWijziging': '2018-07-01T02:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': None},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/10008',
      'title': '10008',
      'id': '10008'},
     'cluster': None,
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/10007',
      'title': '10007',
      'id': '10007'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/348',
      'title': '348',
      'id': '348'},
     'bagHoofdadresVerblijfsobject': None,
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000386',
      'title': '03630980000386',
      'identificatie': '03630980000386'},
     'bagOpenbareruimte': None,
     'bagNummeraanduiding': None},
    'id': '10008',
    'idNummer': 'GL 7225',
    'serienummer': 'BAO01406',
    'clusterId': None,
    'eigenaarId': '184',
    'eigenaarNaam': 'Amsterdam Dump Locatie',
    'status': 0,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2012-03-29',
    'datumPlaatsing': '2012-03-28',
    'datumOperationeel': None,
    'datumAflopenGarantie': '0002-11-29',
    'datumOplevering': '2012-03-28',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': False,
    'locatieId': '10007',
    'geometrie': {'type': 'Point',
     'coordinates': [125258.36436760647, 484073.69760910276]},
    'typeId': '348',
    'bagHoofdadresVerblijfsobjectId': None,
    'gbdBuurtId': '03630980000386',
    'bagOpenbareruimteId': None,
    'bagNummeraanduidingId': None,
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': None,
    'containerUnitCardLezerId': None,
    'containerKleur': 'Hamerslag dennengroen',
    'containerMark': None,
    'containerDatumVervanging': None,
    'containerDatumWijziging': '2018-07-01T02:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': None},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/10010',
      'title': '10010',
      'id': '10010'},
     'cluster': None,
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/10009',
      'title': '10009',
      'id': '10009'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/348',
      'title': '348',
      'id': '348'},
     'bagHoofdadresVerblijfsobject': None,
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000386',
      'title': '03630980000386',
      'identificatie': '03630980000386'},
     'bagOpenbareruimte': None,
     'bagNummeraanduiding': None},
    'id': '10010',
    'idNummer': 'GL 7228',
    'serienummer': 'BAO01407',
    'clusterId': None,
    'eigenaarId': '184',
    'eigenaarNaam': 'Amsterdam Dump Locatie',
    'status': 0,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2012-03-29',
    'datumPlaatsing': '2012-03-28',
    'datumOperationeel': None,
    'datumAflopenGarantie': '0002-11-29',
    'datumOplevering': '2012-03-28',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': False,
    'locatieId': '10009',
    'geometrie': {'type': 'Point',
     'coordinates': [125126.99983269884, 483976.99826622073]},
    'typeId': '348',
    'bagHoofdadresVerblijfsobjectId': None,
    'gbdBuurtId': '03630980000386',
    'bagOpenbareruimteId': None,
    'bagNummeraanduidingId': None,
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': None,
    'containerUnitCardLezerId': None,
    'containerKleur': 'Hamerslag dennengroen',
    'containerMark': None,
    'containerDatumVervanging': None,
    'containerDatumWijziging': '2018-07-01T02:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': None},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/102099',
      'title': '102099',
      'id': '102099'},
     'cluster': None,
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/101949',
      'title': '101949',
      'id': '101949'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/3630',
      'title': '3630',
      'id': '3630'},
     'bagHoofdadresVerblijfsobject': None,
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000174',
      'title': '03630980000174',
      'identificatie': '03630980000174'},
     'bagOpenbareruimte': None,
     'bagNummeraanduiding': None},
    'id': '102099',
    'idNummer': 'GLF33067',
    'serienummer': 'HBD2.018.1094',
    'clusterId': None,
    'eigenaarId': '16',
    'eigenaarNaam': 'F Nieuw-West',
    'status': 0,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2018-04-06',
    'datumPlaatsing': '2018-04-06',
    'datumOperationeel': '2018-04-06',
    'datumAflopenGarantie': '2025-03-01',
    'datumOplevering': '2018-03-01',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': False,
    'locatieId': '101949',
    'geometrie': {'type': 'Point',
     'coordinates': [115581.96347662833, 489440.45949616085]},
    'typeId': '3630',
    'bagHoofdadresVerblijfsobjectId': None,
    'gbdBuurtId': '03630980000174',
    'bagOpenbareruimteId': None,
    'bagNummeraanduidingId': None,
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': None,
    'containerUnitCardLezerId': None,
    'containerKleur': 'NCS7000',
    'containerMark': 10,
    'containerDatumVervanging': '2028-04-06',
    'containerDatumWijziging': '2020-09-16T02:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': None},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/102100',
      'title': '102100',
      'id': '102100'},
     'cluster': None,
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/102101',
      'title': '102101',
      'id': '102101'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/3579',
      'title': '3579',
      'id': '3579'},
     'bagHoofdadresVerblijfsobject': None,
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000168',
      'title': '03630980000168',
      'identificatie': '03630980000168'},
     'bagOpenbareruimte': None,
     'bagNummeraanduiding': None},
    'id': '102100',
    'idNummer': 'GL E 00004',
    'serienummer': '1114',
    'clusterId': None,
    'eigenaarId': '184',
    'eigenaarNaam': 'Amsterdam Dump Locatie',
    'status': 0,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2018-04-09',
    'datumPlaatsing': '2017-03-29',
    'datumOperationeel': None,
    'datumAflopenGarantie': None,
    'datumOplevering': '2017-03-29',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': False,
    'locatieId': '102101',
    'geometrie': {'type': 'Point',
     'coordinates': [119730.63225090025, 486325.0217950056]},
    'typeId': '3579',
    'bagHoofdadresVerblijfsobjectId': None,
    'gbdBuurtId': '03630980000168',
    'bagOpenbareruimteId': None,
    'bagNummeraanduidingId': None,
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': None,
    'containerUnitCardLezerId': None,
    'containerKleur': 'Gris 900 sable',
    'containerMark': 10,
    'containerDatumVervanging': None,
    'containerDatumWijziging': '2018-04-30T02:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': 'na brandschade nieuw huisje geplaatst'},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/102125',
      'title': '102125',
      'id': '102125'},
     'cluster': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/cluster/123143.185%7C487652.743',
      'title': '123143.185|487652.743',
      'id': '123143.185|487652.743'},
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/102115',
      'title': '102115',
      'id': '102115'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/3323',
      'title': '3323',
      'id': '3323'},
     'bagHoofdadresVerblijfsobject': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363020001005327',
      'title': '0363020001005327',
      'identificatie': '0363020001005327'},
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000080',
      'title': '03630980000080',
      'identificatie': '03630980000080'},
     'bagOpenbareruimte': {'href': 'https://api.data.amsterdam.nl/v1/bag/openbareruimtes/0363300000003260',
      'title': '0363300000003260',
      'identificatie': '0363300000003260'},
     'bagNummeraanduiding': {'href': 'https://api.data.amsterdam.nl/v1/bag/nummeraanduidingen/0363200000450029',
      'title': '0363200000450029',
      'identificatie': '0363200000450029'}},
    'id': '102125',
    'idNummer': 'GLA00034',
    'serienummer': 'HBD2.0161574',
    'clusterId': '123143.185|487652.743',
    'eigenaarId': '112',
    'eigenaarNaam': 'A Centrum',
    'status': 1,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2018-04-10',
    'datumPlaatsing': '2018-04-01',
    'datumOperationeel': '2018-04-01',
    'datumAflopenGarantie': '2023-07-01',
    'datumOplevering': '2016-07-01',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': True,
    'locatieId': '102115',
    'geometrie': {'type': 'Point',
     'coordinates': [123142.07521803156, 487653.18641561415]},
    'typeId': '3323',
    'bagHoofdadresVerblijfsobjectId': '0363020001005327',
    'gbdBuurtId': '03630980000080',
    'bagOpenbareruimteId': '0363300000003260',
    'bagNummeraanduidingId': '0363200000450029',
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': '103181100024733',
    'containerUnitCardLezerId': None,
    'containerKleur': 'NCS7000',
    'containerMark': 8,
    'containerDatumVervanging': '2028-04-01',
    'containerDatumWijziging': '2026-03-23T01:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': None},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/102152',
      'title': '102152',
      'id': '102152'},
     'cluster': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/cluster/115332.296%7C486403.224',
      'title': '115332.296|486403.224',
      'id': '115332.296|486403.224'},
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/102151',
      'title': '102151',
      'id': '102151'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/3323',
      'title': '3323',
      'id': '3323'},
     'bagHoofdadresVerblijfsobject': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363010001955796',
      'title': '0363010001955796',
      'identificatie': '0363010001955796'},
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000212',
      'title': '03630980000212',
      'identificatie': '03630980000212'},
     'bagOpenbareruimte': {'href': 'https://api.data.amsterdam.nl/v1/bag/openbareruimtes/0363300000004293',
      'title': '0363300000004293',
      'identificatie': '0363300000004293'},
     'bagNummeraanduiding': {'href': 'https://api.data.amsterdam.nl/v1/bag/nummeraanduidingen/0363200001955414',
      'title': '0363200001955414',
      'identificatie': '0363200001955414'}},
    'id': '102152',
    'idNummer': 'GLF33068',
    'serienummer': 'HBD2.018.0113',
    'clusterId': '115332.296|486403.224',
    'eigenaarId': '16',
    'eigenaarNaam': 'F Nieuw-West',
    'status': 1,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2018-04-10',
    'datumPlaatsing': '2018-04-04',
    'datumOperationeel': '2018-04-04',
    'datumAflopenGarantie': '2025-02-01',
    'datumOplevering': '2018-02-01',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': False,
    'locatieId': '102151',
    'geometrie': {'type': 'Point',
     'coordinates': [115330.9353944899, 486403.8818378381]},
    'typeId': '3323',
    'bagHoofdadresVerblijfsobjectId': '0363010001955796',
    'gbdBuurtId': '03630980000212',
    'bagOpenbareruimteId': '0363300000004293',
    'bagNummeraanduidingId': '0363200001955414',
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': None,
    'containerUnitCardLezerId': None,
    'containerKleur': 'NCS7000',
    'containerMark': 10,
    'containerDatumVervanging': '2028-04-04',
    'containerDatumWijziging': '2019-01-30T01:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': None},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/10236',
      'title': '10236',
      'id': '10236'},
     'cluster': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/cluster/122916.034%7C484851.432',
      'title': '122916.034|484851.432',
      'id': '122916.034|484851.432'},
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/10235',
      'title': '10235',
      'id': '10235'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/382',
      'title': '382',
      'id': '382'},
     'bagHoofdadresVerblijfsobject': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363010000782318',
      'title': '0363010000782318',
      'identificatie': '0363010000782318'},
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000339',

In [121]:
response_test_trash_object["page"]['totalPages']

304

In [120]:
response_test_trash_object["page"]["totalElements"]

30365

In [123]:
response_test3_trash_object["page"]['totalPages']

31

In [124]:
response_test3_trash_object["page"]["totalElements"]

3047

#### Response

In [3]:
url_trash="https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?fractieCode=2"

response_trash = requests.get(url_trash)
print(response_trash.status_code)

info_trash = response_trash.json()
info_trash

200

{'_embedded': {'container': [{'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/10004',
      'title': '10004',
      'id': '10004'},
     'cluster': None,
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/10003',
      'title': '10003',
      'id': '10003'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/348',
      'title': '348',
      'id': '348'},
     'bagHoofdadresVerblijfsobject': None,
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000386',
      'title': '03630980000386',
      'identificatie': '03630980000386'},
     'bagOpenbareruimte': None,
     'bagNummeraanduiding': None},
    'id': '10004',
    'idNummer': 'GL 7226',
    'serienummer': 'BAO01404',
    'clusterId': None,
    'eigenaarId': '184',
    'eigenaarNaam': 'Amsterdam Dump Locatie',
    'status': 0,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2012-03-29',
    'datumPlaatsing': '2012-03-29',
    'datumOperationeel': None,
    'datumAflopenGarantie': '2012-01-01',
    'datumOplevering': '2012-03-29',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': False,
    'locatieId': '10003',
    'geometrie': {'type': 'Point',
     'coordinates': [125270.13808738378, 484296.416385144]},
    'typeId': '348',
    'bagHoofdadresVerblijfsobjectId': None,
    'gbdBuurtId': '03630980000386',
    'bagOpenbareruimteId': None,
    'bagNummeraanduidingId': None,
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': None,
    'containerUnitCardLezerId': None,
    'containerKleur': 'Hamerslag dennengroen',
    'containerMark': None,
    'containerDatumVervanging': None,
    'containerDatumWijziging': '2018-07-01T02:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': None},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/10006',
      'title': '10006',
      'id': '10006'},
     'cluster': None,
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/32498',
      'title': '32498',
      'id': '32498'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/348',
      'title': '348',
      'id': '348'},
     'bagHoofdadresVerblijfsobject': None,
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000386',
      'title': '03630980000386',
      'identificatie': '03630980000386'},
     'bagOpenbareruimte': None,
     'bagNummeraanduiding': None},
    'id': '10006',
    'idNummer': 'GL 7227',
    'serienummer': 'BAO01405',
    'clusterId': None,
    'eigenaarId': '184',
    'eigenaarNaam': 'Amsterdam Dump Locatie',
    'status': 0,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2012-03-29',
    'datumPlaatsing': '2016-01-25',
    'datumOperationeel': '2016-01-25',
    'datumAflopenGarantie': '2016-01-25',
    'datumOplevering': '2012-03-29',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': False,
    'locatieId': '32498',
    'geometrie': {'type': 'Point',
     'coordinates': [125172.99804757624, 484171.99365785054]},
    'typeId': '348',
    'bagHoofdadresVerblijfsobjectId': None,
    'gbdBuurtId': '03630980000386',
    'bagOpenbareruimteId': None,
    'bagNummeraanduidingId': None,
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': None,
    'containerUnitCardLezerId': None,
    'containerKleur': 'Hamerslag dennengroen',
    'containerMark': None,
    'containerDatumVervanging': None,
    'containerDatumWijziging': '2018-07-01T02:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': None},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/10008',
      'title': '10008',
      'id': '10008'},
     'cluster': None,
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/10007',
      'title': '10007',
      'id': '10007'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/348',
      'title': '348',
      'id': '348'},
     'bagHoofdadresVerblijfsobject': None,
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000386',
      'title': '03630980000386',
      'identificatie': '03630980000386'},
     'bagOpenbareruimte': None,
     'bagNummeraanduiding': None},
    'id': '10008',
    'idNummer': 'GL 7225',
    'serienummer': 'BAO01406',
    'clusterId': None,
    'eigenaarId': '184',
    'eigenaarNaam': 'Amsterdam Dump Locatie',
    'status': 0,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2012-03-29',
    'datumPlaatsing': '2012-03-28',
    'datumOperationeel': None,
    'datumAflopenGarantie': '0002-11-29',
    'datumOplevering': '2012-03-28',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': False,
    'locatieId': '10007',
    'geometrie': {'type': 'Point',
     'coordinates': [125258.36436760647, 484073.69760910276]},
    'typeId': '348',
    'bagHoofdadresVerblijfsobjectId': None,
    'gbdBuurtId': '03630980000386',
    'bagOpenbareruimteId': None,
    'bagNummeraanduidingId': None,
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': None,
    'containerUnitCardLezerId': None,
    'containerKleur': 'Hamerslag dennengroen',
    'containerMark': None,
    'containerDatumVervanging': None,
    'containerDatumWijziging': '2018-07-01T02:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': None},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/10010',
      'title': '10010',
      'id': '10010'},
     'cluster': None,
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/10009',
      'title': '10009',
      'id': '10009'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/348',
      'title': '348',
      'id': '348'},
     'bagHoofdadresVerblijfsobject': None,
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000386',
      'title': '03630980000386',
      'identificatie': '03630980000386'},
     'bagOpenbareruimte': None,
     'bagNummeraanduiding': None},
    'id': '10010',
    'idNummer': 'GL 7228',
    'serienummer': 'BAO01407',
    'clusterId': None,
    'eigenaarId': '184',
    'eigenaarNaam': 'Amsterdam Dump Locatie',
    'status': 0,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2012-03-29',
    'datumPlaatsing': '2012-03-28',
    'datumOperationeel': None,
    'datumAflopenGarantie': '0002-11-29',
    'datumOplevering': '2012-03-28',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': False,
    'locatieId': '10009',
    'geometrie': {'type': 'Point',
     'coordinates': [125126.99983269884, 483976.99826622073]},
    'typeId': '348',
    'bagHoofdadresVerblijfsobjectId': None,
    'gbdBuurtId': '03630980000386',
    'bagOpenbareruimteId': None,
    'bagNummeraanduidingId': None,
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': None,
    'containerUnitCardLezerId': None,
    'containerKleur': 'Hamerslag dennengroen',
    'containerMark': None,
    'containerDatumVervanging': None,
    'containerDatumWijziging': '2018-07-01T02:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': None},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/102099',
      'title': '102099',
      'id': '102099'},
     'cluster': None,
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/101949',
      'title': '101949',
      'id': '101949'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/3630',
      'title': '3630',
      'id': '3630'},
     'bagHoofdadresVerblijfsobject': None,
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000174',
      'title': '03630980000174',
      'identificatie': '03630980000174'},
     'bagOpenbareruimte': None,
     'bagNummeraanduiding': None},
    'id': '102099',
    'idNummer': 'GLF33067',
    'serienummer': 'HBD2.018.1094',
    'clusterId': None,
    'eigenaarId': '16',
    'eigenaarNaam': 'F Nieuw-West',
    'status': 0,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2018-04-06',
    'datumPlaatsing': '2018-04-06',
    'datumOperationeel': '2018-04-06',
    'datumAflopenGarantie': '2025-03-01',
    'datumOplevering': '2018-03-01',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': False,
    'locatieId': '101949',
    'geometrie': {'type': 'Point',
     'coordinates': [115581.96347662833, 489440.45949616085]},
    'typeId': '3630',
    'bagHoofdadresVerblijfsobjectId': None,
    'gbdBuurtId': '03630980000174',
    'bagOpenbareruimteId': None,
    'bagNummeraanduidingId': None,
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': None,
    'containerUnitCardLezerId': None,
    'containerKleur': 'NCS7000',
    'containerMark': 10,
    'containerDatumVervanging': '2028-04-06',
    'containerDatumWijziging': '2020-09-16T02:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': None},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/102100',
      'title': '102100',
      'id': '102100'},
     'cluster': None,
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/102101',
      'title': '102101',
      'id': '102101'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/3579',
      'title': '3579',
      'id': '3579'},
     'bagHoofdadresVerblijfsobject': None,
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000168',
      'title': '03630980000168',
      'identificatie': '03630980000168'},
     'bagOpenbareruimte': None,
     'bagNummeraanduiding': None},
    'id': '102100',
    'idNummer': 'GL E 00004',
    'serienummer': '1114',
    'clusterId': None,
    'eigenaarId': '184',
    'eigenaarNaam': 'Amsterdam Dump Locatie',
    'status': 0,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2018-04-09',
    'datumPlaatsing': '2017-03-29',
    'datumOperationeel': None,
    'datumAflopenGarantie': None,
    'datumOplevering': '2017-03-29',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': False,
    'locatieId': '102101',
    'geometrie': {'type': 'Point',
     'coordinates': [119730.63225090025, 486325.0217950056]},
    'typeId': '3579',
    'bagHoofdadresVerblijfsobjectId': None,
    'gbdBuurtId': '03630980000168',
    'bagOpenbareruimteId': None,
    'bagNummeraanduidingId': None,
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': None,
    'containerUnitCardLezerId': None,
    'containerKleur': 'Gris 900 sable',
    'containerMark': 10,
    'containerDatumVervanging': None,
    'containerDatumWijziging': '2018-04-30T02:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': 'na brandschade nieuw huisje geplaatst'},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/102125',
      'title': '102125',
      'id': '102125'},
     'cluster': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/cluster/123143.185%7C487652.743',
      'title': '123143.185|487652.743',
      'id': '123143.185|487652.743'},
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/102115',
      'title': '102115',
      'id': '102115'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/3323',
      'title': '3323',
      'id': '3323'},
     'bagHoofdadresVerblijfsobject': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363020001005327',
      'title': '0363020001005327',
      'identificatie': '0363020001005327'},
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000080',
      'title': '03630980000080',
      'identificatie': '03630980000080'},
     'bagOpenbareruimte': {'href': 'https://api.data.amsterdam.nl/v1/bag/openbareruimtes/0363300000003260',
      'title': '0363300000003260',
      'identificatie': '0363300000003260'},
     'bagNummeraanduiding': {'href': 'https://api.data.amsterdam.nl/v1/bag/nummeraanduidingen/0363200000450029',
      'title': '0363200000450029',
      'identificatie': '0363200000450029'}},
    'id': '102125',
    'idNummer': 'GLA00034',
    'serienummer': 'HBD2.0161574',
    'clusterId': '123143.185|487652.743',
    'eigenaarId': '112',
    'eigenaarNaam': 'A Centrum',
    'status': 1,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2018-04-10',
    'datumPlaatsing': '2018-04-01',
    'datumOperationeel': '2018-04-01',
    'datumAflopenGarantie': '2023-07-01',
    'datumOplevering': '2016-07-01',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': True,
    'locatieId': '102115',
    'geometrie': {'type': 'Point',
     'coordinates': [123142.07521803156, 487653.18641561415]},
    'typeId': '3323',
    'bagHoofdadresVerblijfsobjectId': '0363020001005327',
    'gbdBuurtId': '03630980000080',
    'bagOpenbareruimteId': '0363300000003260',
    'bagNummeraanduidingId': '0363200000450029',
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': '103181100024733',
    'containerUnitCardLezerId': None,
    'containerKleur': 'NCS7000',
    'containerMark': 8,
    'containerDatumVervanging': '2028-04-01',
    'containerDatumWijziging': '2026-03-23T01:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': None},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/102152',
      'title': '102152',
      'id': '102152'},
     'cluster': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/cluster/115332.296%7C486403.224',
      'title': '115332.296|486403.224',
      'id': '115332.296|486403.224'},
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/102151',
      'title': '102151',
      'id': '102151'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/3323',
      'title': '3323',
      'id': '3323'},
     'bagHoofdadresVerblijfsobject': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363010001955796',
      'title': '0363010001955796',
      'identificatie': '0363010001955796'},
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000212',
      'title': '03630980000212',
      'identificatie': '03630980000212'},
     'bagOpenbareruimte': {'href': 'https://api.data.amsterdam.nl/v1/bag/openbareruimtes/0363300000004293',
      'title': '0363300000004293',
      'identificatie': '0363300000004293'},
     'bagNummeraanduiding': {'href': 'https://api.data.amsterdam.nl/v1/bag/nummeraanduidingen/0363200001955414',
      'title': '0363200001955414',
      'identificatie': '0363200001955414'}},
    'id': '102152',
    'idNummer': 'GLF33068',
    'serienummer': 'HBD2.018.0113',
    'clusterId': '115332.296|486403.224',
    'eigenaarId': '16',
    'eigenaarNaam': 'F Nieuw-West',
    'status': 1,
    'fractieCode': '2',
    'fractieOmschrijving': 'Glas',
    'datumCreatie': '2018-04-10',
    'datumPlaatsing': '2018-04-04',
    'datumOperationeel': '2018-04-04',
    'datumAflopenGarantie': '2025-02-01',
    'datumOplevering': '2018-02-01',
    'wijzigingsdatumDp': '2026-06-11T00:00:00',
    'verwijderdDp': False,
    'geadopteerdInd': False,
    'locatieId': '102151',
    'geometrie': {'type': 'Point',
     'coordinates': [115330.9353944899, 486403.8818378381]},
    'typeId': '3323',
    'bagHoofdadresVerblijfsobjectId': '0363010001955796',
    'gbdBuurtId': '03630980000212',
    'bagOpenbareruimteId': '0363300000004293',
    'bagNummeraanduidingId': '0363200001955414',
    'containerRalKleurNaam': None,
    'containerRalKleurCode': None,
    'containerRalKleurHexcode': None,
    'containerChipNummber': None,
    'containerUnitCardLezerId': None,
    'containerKleur': 'NCS7000',
    'containerMark': 10,
    'containerDatumVervanging': '2028-04-04',
    'containerDatumWijziging': '2019-01-30T01:00:00',
    'containerEndOfLife': None,
    'containerEigenaarschap': 'Eigendom',
    'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
    'containerOpmerking': None},
   {'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
     'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/10236',
      'title': '10236',
      'id': '10236'},
     'cluster': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/cluster/122916.034%7C484851.432',
      'title': '122916.034|484851.432',
      'id': '122916.034|484851.432'},
     'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/10235',
      'title': '10235',
      'id': '10235'},
     'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/382',
      'title': '382',
      'id': '382'},
     'bagHoofdadresVerblijfsobject': {'href': 'https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363010000782319',
      'title': '0363010000782319',
      'identificatie': '0363010000782319'},
     'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000339',

In [4]:
info_trash['_embedded'].keys()

dict_keys(['container'])

In [8]:
len(info_trash['_embedded']['container'])

20

In [6]:
info_trash['_embedded']['container'][0]

{'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
  'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/10004',
   'title': '10004',
   'id': '10004'},
  'cluster': None,
  'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/10003',
   'title': '10003',
   'id': '10003'},
  'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/348',
   'title': '348',
   'id': '348'},
  'bagHoofdadresVerblijfsobject': None,
  'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000386',
   'title': '03630980000386',
   'identificatie': '03630980000386'},
  'bagOpenbareruimte': None,
  'bagNummeraanduiding': None},
 'id': '10004',
 'idNummer': 'GL 7226',
 'serienummer': 'BAO01404',
 'clusterId': None,
 'eigenaarId': '184',
 'eigenaarNaam': 'Amsterdam Dump Locatie',
 'status': 0,
 'fractieCode': '2',
 'fractieOmschrijving': 'Glas',
 'datumCreatie': '2012-03-29',
 'datumPlaatsing': '2012-03-29',
 'datumOperationeel': None,
 'datumAflopenGarantie': '2012-01-01',
 'datumOplevering': '2012-03-29',
 'wijzigingsdatumDp': '2026-06-11T00:00:00',
 'verwijderdDp': False,
 'geadopteerdInd': False,
 'locatieId': '10003',
 'geometrie': {'type': 'Point',
  'coordinates': [125270.13808738378, 484296.416385144]},
 'typeId': '348',
 'bagHoofdadresVerblijfsobjectId': None,
 'gbdBuurtId': '03630980000386',
 'bagOpenbareruimteId': None,
 'bagNummeraanduidingId': None,
 'containerRalKleurNaam': None,
 'containerRalKleurCode': None,
 'containerRalKleurHexcode': None,
 'containerChipNummber': None,
 'containerUnitCardLezerId': None,
 'containerKleur': 'Hamerslag dennengroen',
 'containerMark': None,
 'containerDatumVervanging': None,
 'containerDatumWijziging': '2018-07-01T02:00:00',
 'containerEndOfLife': None,
 'containerEigenaarschap': 'Eigendom',
 'containerEigenaarschapOpmerking': 'Container is in eigendom van de klant',
 'containerOpmerking': None}

In [11]:
info_trash['_embedded']['container'][19]

{'_links': {'schema': 'https://schemas.data.amsterdam.nl/datasets/huishoudelijkafval/container/v2',
  'self': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container/10254',
   'title': '10254',
   'id': '10254'},
  'cluster': None,
  'locatie': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containerlocatie/10253',
   'title': '10253',
   'id': '10253'},
  'type': {'href': 'https://api.data.amsterdam.nl/v1/huishoudelijkafval/containertype/382',
   'title': '382',
   'id': '382'},
  'bagHoofdadresVerblijfsobject': None,
  'gbdBuurt': {'href': 'https://api.data.amsterdam.nl/v1/gebieden/buurten/03630980000340',
   'title': '03630980000340',
   'identificatie': '03630980000340'},
  'bagOpenbareruimte': None,
  'bagNummeraanduiding': None},
 'id': '10254',
 'idNummer': 'GL 7144',
 'serienummer': 'BAO01529',
 'clusterId': None,
 'eigenaarId': '184',
 'eigenaarNaam': 'Amsterdam Dump Locatie',
 'status': 0,
 'fractieCode': '2',
 'fractieOmschrijving': 'Glas',
 'datumCreatie': '2012-03-29',
 'datumPlaatsing': '2012-03-29',
 'datumOperationeel': None,
 'datumAflopenGarantie': '2012-01-01',
 'datumOplevering': '2012-03-29',
 'wijzigingsdatumDp': '2026-06-11T00:00:00',
 'verwijderdDp': False,
 'geadopteerdInd': False,
 'locatieId': '10253',
 'geometrie': {'type': 'Point',
  'coordinates': [123356.1227815991, 485416.0519603118]},
 'typeId': '382',
 'bagHoofdadresVerblijfsobjectId': None,
 'gbdBuurtId': '03630980000340',
 'bagOpenbareruimteId': None,
 'bagNummeraanduidingId': None,
 'containerRalKleurNaam': 'Fir green',
 'containerRalKleurCode': '6009',
 'containerRalKleurHexcode': '31372B',
 'containerChipNummber': None,
 'containerUnitCardLezerId': None,
 'containerKleur': 'Dennengroen (RAL 6009)',
 'containerMark': None,
 'containerDatumVervanging': None,
 'containerDatumWijziging': '2018-07-01T02:00:00',
 'containerEndOfLife': None,
 'containerEigenaarschap': None,
 'containerEigenaarschapOpmerking': None,
 'containerOpmerking': None}

In [7]:
info_trash['_embedded']['container'][0]['geometrie']['coordinates']

[125270.13808738378, 484296.416385144]

#### Iteration through pages

In [21]:
all_records_glass_trash = []
page = 1

url_trash_pagination = "https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?fractieCode=2&_pageSize=100"

while url_trash_pagination:

    print(f"Downloading page {page}")

    response_page = requests.get(url_trash_pagination)
    response_page.raise_for_status()

    info_page = response_page.json()

    embedded = info_page["_embedded"]
    collection = next(iter(embedded))

    missing_geometry = 0
    for container in embedded[collection]:
        geometrie = container.get("geometrie")
        if geometrie is None:
            missing_geometry += 1
            continue
        if geometrie and "coordinates" in geometrie:
            all_records_glass_trash.append(geometrie["coordinates"])
    
    # Get the URL for the next page (if any)
    url_trash_pagination = info_page["_links"].get("next", {}).get("href")
    print(url_trash_pagination)

    page += 1

Downloading page 1
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=2
Downloading page 2
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=3
Downloading page 3
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=4
Downloading page 4
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=5
Downloading page 5
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=6
Downloading page 6
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=7
Downloading page 7
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=8
Downloading page 8
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=9
Downloading page 9
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=10
Downloading page 10
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=11
Downloading page 11
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=12
Downloading page 12
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=13
Downloading page 13
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=14
Downloading page 14
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=15
Downloading page 15
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=16
Downloading page 16
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=17
Downloading page 17
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=18
Downloading page 18
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=19
Downloading page 19
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=20
Downloading page 20
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=21
Downloading page 21
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=22
Downloading page 22
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=23
Downloading page 23
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=24
Downloading page 24
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=25
Downloading page 25
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=26
Downloading page 26
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=27
Downloading page 27
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=28
Downloading page 28
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=29
Downloading page 29
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=30
Downloading page 30
https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=31
Downloading page 31
None

In [17]:
url_pagination = info_page["_links"].get("next", {}).get("href")
url_pagination

'https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?_pageSize=100&fractieCode=2&page=2'

#### Transform to Data Frame¶

In [22]:
len(all_records_glass_trash)

2980

In [29]:
glass_trash_data = pd.DataFrame(all_records_glass_trash)

In [24]:
glass_trash_data

                  0              1
0     125270.138087  484296.416385
1     125172.998048  484171.993658
2     125258.364368  484073.697609
3     125126.999833  483976.998266
4     115581.963477  489440.459496
...             ...            ...
2975  123068.998130  485428.993694
2976  123258.066508  485508.365730
2977  123471.443863  485604.969668
2978  123584.995591  485665.999347
2979  123057.059892  485597.151651

[2980 rows x 2 columns]

In [30]:
glass_trash_data['object'] = 'glass_trash_can'

In [34]:
glass_trash_data = glass_trash_data[['object', 0, 1]]

In [35]:
glass_trash_data

               object              0              1
0     glass_trash_can  125270.138087  484296.416385
1     glass_trash_can  125172.998048  484171.993658
2     glass_trash_can  125258.364368  484073.697609
3     glass_trash_can  125126.999833  483976.998266
4     glass_trash_can  115581.963477  489440.459496
...               ...            ...            ...
2975  glass_trash_can  123068.998130  485428.993694
2976  glass_trash_can  123258.066508  485508.365730
2977  glass_trash_can  123471.443863  485604.969668
2978  glass_trash_can  123584.995591  485665.999347
2979  glass_trash_can  123057.059892  485597.151651

[2980 rows x 3 columns]

## CSV

#### Load dataframe

In [38]:
housing_units = pd.read_csv(
    "BAG_verblijfsobject_Actueel.csv",
    sep=";",
    low_memory=False
)

In [39]:
housing_units.head()

,identificatie,aanduidingInOnderzoek,geconstateerd,heeftIn:BAG.NAG.identificatieHoofdadres,huisnummerHoofdadres,huisletterHoofdadres,huisnummertoevoegingHoofdadres,postcodeHoofdadres,ligtAan:BAG.ORE.identificatieHoofdadres,ligtAan:BAG.ORE.naamHoofdadres,...,ligtIn:GBD.GGW.code,ligtIn:GBD.GGW.naam,ligtIn:GBD.GGP.identificatie,ligtIn:GBD.GGP.code,ligtIn:GBD.GGP.naam,ligtIn:GBD.SDL.identificatie,ligtIn:GBD.SDL.code,ligtIn:GBD.SDL.naam,geometrie,bagproces
0,363010000543292,N,N,363200000006110,1,NaN,H,1015NR,363300000002529,Eerste Anjeliersdwarsstraat,...,GA01,Centrum-West,NaN,NaN,NaN,3630000000018,A,Centrum,POINT (120700 487936),NaN
1,363010000543300,N,N,363200000006119,5,NaN,1,1015NR,363300000002529,Eerste Anjeliersdwarsstraat,...,GA01,Centrum-West,NaN,NaN,NaN,3630000000018,A,Centrum,POINT (120703 487926),Muteren naar aanleiding van signalering
2,363010000543305,N,N,363200000006124,7,NaN,2,1015NR,363300000002529,Eerste Anjeliersdwarsstraat,...,GA01,Centrum-West,NaN,NaN,NaN,3630000000018,A,Centrum,POINT (120705 487922),Muteren naar aanleiding van signalering
3,363010000543308,N,N,363200000403263,17,NaN,NaN,1015NR,363300000002529,Eerste Anjeliersdwarsstraat,...,GA01,Centrum-West,NaN,NaN,NaN,3630000000018,A,Centrum,POINT (120709 487918),Muteren naar aanleiding van signalering
4,363010000543318,N,N,363200000006133,29,NaN,NaN,1015NR,363300000002529,Eerste Anjeliersdwarsstraat,...,GA01,Centrum-West,NaN,NaN,NaN,3630000000018,A,Centrum,POINT (120708 487907),Muteren naar aanleiding van signalering

In [40]:
housing_units.info()

<class 'pandas.DataFrame'>
RangeIndex: 582145 entries, 0 to 582144
Data columns (total 55 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   identificatie                            582145 non-null  int64
 1   aanduidingInOnderzoek                    582145 non-null  str
 2   geconstateerd                            582145 non-null  str
 3   heeftIn:BAG.NAG.identificatieHoofdadres  582145 non-null  int64
 4   huisnummerHoofdadres                     582145 non-null  int64
 5   huisletterHoofdadres                     114673 non-null  str
 6   huisnummertoevoegingHoofdadres           186805 non-null  str
 7   postcodeHoofdadres                       572341 non-null  str
 8   ligtAan:BAG.ORE.identificatieHoofdadres  582145 non-null  int64
 9   ligtAan:BAG.ORE.naamHoofdadres           582145 non-null  str
 10  ligtIn:BAG.WPS.identificatieHoofdadres   582145 non-null  int64
 11  ligtIn:BAG.WPS.naamHoofdadres            582145 non-null  str
 12  ligtIn:BRK.GME.identificatie             582145 non-null  int64
 13  ligtIn:BRK.GME.naam                      582145 non-null  str
 14  heeftIn:BAG.NAG.identificatieNevenadres  1581 non-null    str
 15  gebruiksdoel                             582145 non-null  str
 16  gebruiksdoelWoonfunctie                  25865 non-null   str
 17  gebruiksdoelGezondheidszorgfunctie       254 non-null     str
 18  aantalEenhedenComplex                    6887 non-null    float64
 19  is:WOZ.WOB.soortObject                   546470 non-null  str
 20  oppervlakte                              582145 non-null  int64
 21  status                                   582145 non-null  str
 22  beginGeldigheid                          582145 non-null  str
 23  eindGeldigheid                           0 non-null       float64
 24  documentdatum                            582145 non-null  str
 25  documentnummer                           582145 non-null  str
 26  verdiepingToegang                        548614 non-null  float64
 27  toegang                                  297868 non-null  str
 28  aantalBouwlagen                          536724 non-null  float64
 29  hoogsteBouwlaag                          193680 non-null  float64
 30  laagsteBouwlaag                          193680 non-null  float64
 31  aantalKamers                             509057 non-null  float64
 32  eigendomsverhouding                      0 non-null       float64
 33  redenopvoer                              36241 non-null   str
 34  redenafvoer                              31 non-null      str
 35  ligtIn:BAG.PND.identificatie             582145 non-null  str
 36  ligtIn:GBD.BBK.identificatie             566456 non-null  float64
 37  ligtIn:GBD.BBK.code                      566456 non-null  str
 38  ligtIn:GBD.BRT.identificatie             582145 non-null  int64
 39  ligtIn:GBD.BRT.code                      582145 non-null  str
 40  ligtIn:GBD.BRT.naam                      582145 non-null  str
 41  ligtIn:GBD.WIJK.identificatie            582145 non-null  int64
 42  ligtIn:GBD.WIJK.code                     578119 non-null  str
 43  ligtIn:GBD.WIJK.naam                     582145 non-null  str
 44  ligtIn:GBD.GGW.identificatie             580380 non-null  float64
 45  ligtIn:GBD.GGW.code                      580380 non-null  str
 46  ligtIn:GBD.GGW.naam                      580380 non-null  str
 47  ligtIn:GBD.GGP.identificatie             0 non-null       float64
 48  ligtIn:GBD.GGP.code                      0 non-null       float64
 49  ligtIn:GBD.GGP.naam                      0 non-null       float64
 50  ligtIn:GBD.SDL.identificatie             582145 non-null  int64
 51  ligtIn:GBD.SDL.code                      582145 non-null  str
 52  ligtIn:GBD.SDL.naam                      582145 non-null  str
 53  geometrie                                582145 non-null  str
 54  bagproces                                396896 non-null  str
dtypes: float64(13), int64(10), str(32)
memory usage: 244.3 MB

## Context

Amsterdam spans approximately 16,748 unique 6-digit postal codes (e.g., 1012 JS). These are distributed across roughly 75 unique 4-digit district areas (e.g., 1012). Each specific 6-digit postcode generally covers an average of just 15 to 20 individual addresses.

https://www.amsterdam.nl/stelselpedia/bag-index/producten-bag/prodspec-postcode/

Postal codes in Amsterdam fall within the 1000 to 1109 range. They are divided across the city's seven main districts and Weesp as follows:

- Centrum (1011 - 1019): Covers the historic inner city, canals, and the Eastern Docklands.
- Noord (1020 - 1039): Situated directly across the IJ river.
- Westpoort (1040 - 1049): Amsterdam's primary port and industrial area.
- West (1050 - 1059): Neighborhoods just west of the Singelgracht.
- Nieuw-West (1060 - 1069): Residential areas extending towards the western outskirts.
- Zuid (1070 - 1083): Includes De Pijp, Oud-Zuid, and the Zuidas business district.
- Oost (1086 - 1099): The eastern residential boroughs.
- Zuidoost (1100 - 1109): The southeastern region, including the Bijlmer and Gaasperplas.
https://nl.wikipedia.org/wiki/Lijst_van_postcodes_1000-1999_in_Nederland